### ISSUE TITLE
undo/redo issue

### ISSUE THREAD

**Issue by GayathriD2020** [artf/grapesjs#2525] opened 2020-01-24 07:04 UTC
Hi,
I'm facing undo and redo issue, let's assume i have a text block like **Insert text here**  i'm gonna change into **Hello** then click an undo button it shows a **Insert text here** again i'll click a redo button it comes like **Insert text hereHello**.

Please give me any solution to overcome this.

**Comment by pouyamiralayi** [comment] 2020-01-25 10:18
@GayathriD2020  i can not reproduce this on the demo. are you on the latest version?
Cheers!

**Comment by GayathriD2020** [comment] 2020-01-27 03:57
@pouyamiralayi  I updated the latest version of grapesjs **(0.15.10)** still  undo and redo functionality not working.

**Comment by pouyamiralayi** [comment] 2020-01-27 13:24
@GayathriD2020 grapesjs is using [backbone-undo](http://osartun.github.io/Backbone.Undo.js/) under the hood and here is the src for [grapesjs undo manager](https://github.com/artf/grapesjs/blob/dev/src/undo_manager/index.js)
Cheers!

**Comment by GayathriD2020** [comment] 2020-01-28 04:41
Thanks for the reference, I will check with that and if i need any assist let you know. Have a great day

**Comment by artf** [comment] 2020-02-03 08:31
Not able to reproduce it, I'll close it for now

**Closed by artf** 2020-02-03 08:31 UTC
