### ISSUE TITLE
[BUG]: destroy() method didn't fully remove events

### ISSUE THREAD

**Issue by wemod123** [artf/grapesjs#2681] opened 2020-03-24 12:48 UTC
version: latest: v-0.16.3.

**important**: update from v-0.15.9 to v-0.16.3 while keep everything same, the error will show in console:
```
Uncaught TypeError: Cannot read property 'frameElement' of null
    at r.getFrameOffset (grapes.min.js?a826:formatted:28973)
    at r.getElementPos (grapes.min.js?a826:formatted:28985)
    at r.getElementPos (grapes.min.js?a826:formatted:13792)
    at r.updateLocalPos (grapes.min.js?a826:formatted:13444)
    at r.onFrameUpdated (grapes.min.js?a826:formatted:13396)
    at I (grapes.min.js?a826:formatted:554)
    at eval (grapes.min.js?a826:formatted:566)
    at eval (grapes.min.js?a826:formatted:129)
    ....
```

This error show there is a errro in function `getFrameOffset`, near position: `e.ownerDocument.defaultView.frameElement`:

```
...
clearOff: function() {
   this.frmOff = null,
   this.cvsOff = null
},
getFrameOffset: function(e) {
   if (!this.frmOff || e) {
>>> var t = e ? e.ownerDocument.defaultView.frameElement : this.frame.el;
       this.frmOff = this.offset(t)
  }
  return this.frmOff
 },
getCanvasOffset: function() {
   return this.cvsOff || (this.cvsOff = this.offset(this.el)),
  this.cvsOff
}
...
```
Refer to [This Code Line](https://github.com/artf/grapesjs/blob/4c1e74c8d2b75d2c1cdbd59f288cf75d7d2aa690/src/canvas/view/CanvasView.js#L173)

Checking the error stack will track to [This Code Line](https://github.com/artf/grapesjs/blob/e18a336bc85fbe1d87aae7889f1a7326c77a8305/src/commands/view/SelectComponent.js#L136)

**Expected:** no error reported.
**Impact:** I do not get specific negitive impact, only show the error.
**Reproduce:**  I integrate with Vue usage + webpack, hard to really reproduce, to debug this probaly check:
1. simply add check chain to avoid `TypeError`:

```
before: var t = e ? e.ownerDocument.defaultView.frameElement : this.frame.el;
after: var t= (e && e.ownerDocument && e.ownerDocument.defaultView &&  e.ownerDocument.defaultView.frameElement) || this.frame.el;
```
2. if this `frameElement` is required, in what condition it will missing, and then cause error.

**Comment by artf** [comment] 2020-04-03 11:59
Thanks for the report @wemod123 Are you able to create a reproducible live demo of the issue?

**Comment by wemod123** [comment] 2020-04-18 03:16
@artf 

To create this issue, simply go to demo page : https://grapesjs.com/demo.html

1.  Press F12
2.  Go to 'Element' tab, find the html document node, ` <div id="gjs" ... `, and right click, select `Delete element`
3. Now when you resize the window, the error will apear in console.

This issue is caused by window events still there while the target gjs editor container is not exist.

To solve this issue, press F5 to reload the page, and switch to tab `Console`, input:  `grapesjs.editors[0].destroy()`, will destroy the instance, and then, delete the dom node as previous step 2, now when you resize window will not have any error.

Summary:
I use Vue component to init grapesjs instance, when router changes, the target editor dom is removed but editor instanc still exist, will have error, 

To solve this need to first destroy instance and then remove the dom node, **but I had not secceed so far**, it's more related to my Vue skill, since the `destroy()` methods is works fine, I believe there should be same issue if you having dom add/remove operations in simillar frame work linek Angular/React

**Comment by wemod123** [comment] 2020-04-18 03:19
@artf I propose to close this issue after your confirmation, and if you do not have further comments.

**Comment by wemod123** [comment] 2020-05-06 02:08
@artf 

Updates with latest version: v-0.16.12.

The previous error: `Uncaught TypeError: Cannot read property 'frameElement' of null` disapeared, but there is a new error: `TypeError: Cannot read property 'models' of undefined`

Reproduce:

1. Open the demon page: https://grapesjs.com/demo.html.
2. make some change, e.x. drag and drop a block into canvas.
3. Press F12, go to `Console` Tab
4. Input `grapesjs.editors[0].destroy()`

Will get error `TypeError: Cannot read property 'models' of undefined`

I'am very new to grapesjs, didnt fully understand the source code yet,
hope this helpful for further debug,

**Comment by mattdeigh** [comment] 2020-05-07 20:08
I've noticed this too. Looks like it's specific to destroying the editor while something is selected. Not sure where the call is originally, but I was able to get around it by calling ```editor.select()``` and putting the destroy in a ```setTimeout```.
```js
editor.select();
setTimeout(() => {
  editor.destroy();
}, 0);
```
I'm using Turbolinks, so for me I have a ```before-visit``` event listener that I listen to, prevent it from navigating away, then trigger the visit after everything has been destroyed.

Example:
```js
document.addEventListener('turbolinks:before-visit', (event) => {
  event.preventDefault();
  editor.select();
  setTimeout(() => {
    editor.destroy();
    Turbolinks.visit(url);
  }, 0);
});
```
Code is an example from what I have running right now. You'll want to cleanup the even listener after it's called, or else you'd be in a loop.

Not positive, but it looks like the error could be ignored since it looks like it's called outside of the main javascript thread or whatever that's called. One option for fixing this might be changing ```Editor.js``` on [ln 289](https://github.com/artf/grapesjs/blob/dev/src/editor/model/Editor.js#L289) to this:
```js
  getSelectedAll() {
    const selected = this.get('selected');
    return selected && selected.models || [];
  },
```
Though cleaning up the call so it doesn't get called in the first place might be the right way to handle it.

**Comment by wemod123** [comment] 2020-05-10 06:19
@mattdeigh Thank you, your solution works for me:

```
  editor.select();
  setTimeout(() => {
    editor.destroy();
  }, 0);
```

Then I close this topic at the moment.

**Comment by neon12345** [comment] 2020-08-11 16:51
I think this should be reopened and properly fixed in destroy.

The problem is with debounce of some events.
At the time the events are removed in destroy, they are already fired and debounced.
The editor is then already gone when the debounce finish. 
The setTimeout after the "editor.select();" will queue the destroy after the debounced events to avoid the error.

**Comment by emilsedgh** [comment] 2022-01-06 03:48
I agree that this needs to be reopened and fixed within the destroy function itself.

**Closed** 2022-01-11 15:19 UTC
Labels: bug, help wanted

**Comment by emilsedgh** [comment] 2022-01-31 19:30
Thank you @artf ! 🙏
