### ISSUE TITLE
BUG: StyleManager AppendTo not showing in custom div

### ISSUE THREAD

**Issue by paooolino** [artf/grapesjs#3835] opened 2021-09-29 16:09 UTC
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome 93

### Reproducible demo link

https://codepen.io/paooolino/pen/WNOPgJy

### Describe the bug

**How to reproduce the bug?**
This is quite simple because I was using Grapes v.0.16.xx and it worked until I upgraded to the latest release and my StyleManager panel disappeared. I can provide a codepen with previous version (working)
https://codepen.io/paooolino/pen/jOwdvZv

and then another one with identical code but upgraded library (not working)
https://codepen.io/paooolino/pen/WNOPgJy

The code is quite simple because I just need to show the styleManager in a custom div with some sectors defined.

I looked for similar issues but I didnt found my case. I also tried with appendTo: '#panels' either with dom element as in the codepens.

**What is the expected behavior?**
The styleManager should be shown in the defined #panels div.

**What is the current behavior?**
The styleManager does not shows.

Maybe I missed something?
Thankyou for your attention.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by paooolino** [comment] 2021-09-30 06:36
I verified it is since v0.17.25

v0.17.22 >>> working
v0.17.25 >>> not working

**Comment by artf** [comment] 2021-10-04 14:34
Thanks Paolo, that will be fixed in the next release.
The problem is with the default StyleManager opener command, which moves the rendered part, from your container, to the default one.
You can verify that by disabling the default button which activates the command (which moves the element once pressed).
```js
editor.Panels.getButton('views', 'open-sm').set('active', false);
```
So, as a workaround, you should delete it or hide it with CSS
```js
editor.Panels.removeButton('views', 'open-sm');
```

**Closed** 2021-10-04 14:47 UTC
Labels: bug

**Comment by paooolino** [comment] 2021-10-06 14:18
thankyou for the release. And sorry for reopening :-) but now the StyleManager appendTo is working, while the blockManager appendTo appears to be broken. Same problem with the previous StyleManager. I verified it was working in previous v.0.17.26 but now v.0.17.27 is not showing. 🙏

**Comment by artf** [comment] 2021-10-06 14:46
yeah Paolo, I'd appreciate a codepen, please. I've updated appendTo of all the openers and it was working as expected in all cases.

**Comment by artf** [comment] 2021-10-06 15:21
Ok, I got it, forgot to update one thing 😅  fix already in for the next release.
As a temporary patch, add this post init
```js
editor.onReady(() => editor.Blocks.render())
```

**Comment by paooolino** [comment] 2021-10-06 15:28
great, thankyou 👍

**Comment by mingxin-yang** [comment] 2021-10-09 08:34
> Ok, I got it, forgot to update one thing 😅 fix already in for the next release. As a temporary patch, add this post init
> 
> ```js
> editor.onReady(() => editor.Blocks.render())
> ```

After add this code, it also doesn't work.

**Comment by mingxin-yang** [comment] 2021-11-09 06:30
I corrected the code so that it can run, because I added the grapesjs-mjml plug-in, which contains blocks. I can’t load blocks in grapesjs.init. Then I use editor.BlockManager.add() to add blocks.

But I don’t know why the new version changed 

@paooolino @artf

**Comment by paooolino** [comment] 2021-11-09 06:44
again, you didn't answer to the previous questions nor provided a codepen. It will be easier to help.

**Comment by mingxin-yang** [comment] 2021-11-09 06:47
https://codepen.io/paooolino/pen/GREVmKR 
@paooolino

**Comment by mingxin-yang** [comment] 2021-11-09 06:48
I know how to correct it now
