### ISSUE TITLE
Drag and drop issue  in dragMode of translate

### ISSUE THREAD

**Issue by ramusesan** [artf/grapesjs#2473] opened 2019-12-26 12:31 UTC
there is an issue am facing (seems offset issue) while trying and hold and drag the toolbar's move icon

i have added bootstrap and columns (**col-sm-2 & col-sm-10**) then trying to hold the targeted component and dragging its working fine. 
but it doesn't work properly when I try to drag the component by holding move icon of toolbar **_i.e cursor position and component position getting more distance between
_**
but if I click on the full-screen button or use **col-sm-12** (full width) and try two drag and drop works fine 

I have attached below the live demo 

![GrapesJS](https://user-images.githubusercontent.com/15937743/71476333-88e95b00-280a-11ea-9ed4-dd7789fbe008.gif)

**Comment by ramusesan** [comment] 2019-12-30 06:53
could anyone help on this

**Comment by MartinPutz** [comment] 2019-12-30 08:26
@ramusesan might be related to this issue: #2423 hopefully the refactored canvas will solve these issues
As @artf suggested on that issue you could try this branch: https://github.com/artf/grapesjs/tree/multi-frame

**Comment by pouyamiralayi** [comment] 2019-12-30 10:17
hi @ramusesan here is the [PR](https://github.com/artf/grapesjs/pull/2375).
cheers!

**Comment by ramusesan** [comment] 2019-12-30 12:10
thank you guys @MartinPutz @pouyamiralayi

**Comment by artf** [comment] 2020-01-02 17:00
Thanks for the report @ramusesan I close this as a duplicate of #2207
Changes in the PR will be available in the next release

**Closed by artf** 2020-01-02 17:00 UTC

**Comment by motazad** [comment] 2020-05-28 12:04
> Thanks for the report @ramusesan I close this as a duplicate of #2207
> Changes in the PR will be available in the next release

@artf 
When will this feature be added?
It really is necessary

**Comment by amarjeet16ril** [comment] 2022-02-10 07:48
Drag mode translate X and Y in pixel, for responsive how we can set with % X and Y coordinates
