### ISSUE TITLE
Images won't resize to full width

### ISSUE THREAD

**Issue by benvmatheson** [artf/grapesjs#2002] opened 2019-05-07 23:28 UTC
When an image is resized with the mouse, it won't stretch all the way to the edge of the canvas, leaving a white space on the right side. If adjusting Dimensions --> Width, you can bring it all the way to the edge of the canvas.

![image](https://user-images.githubusercontent.com/9043745/57339111-75f41000-70ed-11e9-9d54-0d413f181940.png)

If you drag enough elements onto the canvas for the scrollbar to appear, the scrollbar fills the white space that the image wouldn't fill. It appears the dragging is just taking the scroll bar into consideration and won't fill the scroll bar's area, even if the scroll bar doesn't exist yet.

![image](https://user-images.githubusercontent.com/9043745/57339104-6b397b00-70ed-11e9-8ea4-b90a69be4ccc.png)

https://jsfiddle.net/benvmatheson/2r3jdfpa/6/

**Comment by artf** [comment] 2019-05-11 17:33
Not sure but it might also be an issue in the resizer configuration https://github.com/artf/grapesjs/blob/3f053af969ef6a688d526d158b9df7e6aa076838/src/commands/view/SelectComponent.js#L353

**Comment by giorgiosjames** [comment] 2019-06-28 03:44
This seems to be caused by the padding value here:
https://github.com/artf/grapesjs/blob/3f053af969ef6a688d526d158b9df7e6aa076838/src/commands/view/SelectComponent.js#L449
Setting this value to 0 allows me to resize components right to the edge of the canvas.

**Comment by benvmatheson** [comment] 2019-08-23 19:01
This issue appears to still exist on 0.15.3.

**Comment by artf** [comment] 2019-08-26 22:29
Seems like I totally forget about this issue 😂 thanks to @benvmatheson for the ping.
I apologize also to @giorgiosjames for totally ignoring his PR 😬 even because I have to close it as he is right, we can do it correctly and dynamically without relying on some kind of option (just need to get the width of the body instead of the iframe).
The fix will be available in the next release

**Comment by giorgiosjames** [comment] 2019-08-26 22:38
@artf No worries. Glad to see this fixed in a more concrete way.

**Closed** 2019-08-26 22:58 UTC
Labels: enhancement, help wanted
