### ISSUE TITLE
Countdown time is not working correctly

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1060] opened 2018-04-24 06:10 UTC
Hi artf,

Please find the below video reflecting countdown issue:
https://vimeo.com/266054022

Please review it once and let me know if need further assistance in countdown issue understanding.

**Comment by artf** [comment] 2018-04-25 10:01
Duplicate of https://github.com/artf/grapesjs-component-countdown/issues/4

**Closed by artf** 2018-04-25 10:01 UTC
