### ISSUE TITLE
Blocks Manager in GrapesJS Not Working For Columns

### ISSUE THREAD

**Issue by brandonburr86** [artf/grapesjs#543] opened 2017-11-19 00:00 UTC
Hello,

My installation of GJS ties in all of the default blocks. Every block drags fine onto the page with the exception of all the "columns". i.e: 1,2, and 3 columns. When I drag them.. it does nothing. 

What should I do?

Brandon

**Comment by brandonburr86** [comment] 2017-11-19 00:23
I see in the inspector that the "row" css class is non-existent. I checked the demo and see that the "row" css class is put in dynamically into the "gjs-css-rules" block.

**Comment by artf** [comment] 2017-11-20 13:41
@brandonburr86 about what demo are you talking about?

**Comment by brandonburr86** [comment] 2017-11-21 11:57
http://grapesjs.com/demo.html

**Comment by artf** [comment] 2017-11-22 20:48
Hey @brandonburr86 try to reset the cache of your browser and retry because I don't see any error
![blocks](https://user-images.githubusercontent.com/11614725/33149130-cfa87e4a-cfce-11e7-8f31-53ffa6bc8b83.gif)

**Comment by brandonburr86** [comment] 2017-11-22 22:39
No the demo works fine, but it doesn't work in my app. Here is a screen capture video of the issue.
[GrapesJS issue](https://s3.amazonaws.com/burrfiles/grapesjs-issue.mov)

**Comment by brandonburr86** [comment] 2017-11-22 22:40
Also I did try clearing the cache and launching my app in private mode. Still didn't work.

**Comment by artf** [comment] 2017-11-22 22:47
I think the source of the issue is the basic block plugin
https://github.com/artf/grapesjs-blocks-basic/blob/master/src/index.js#L28
those styles should be placed inside their relative blocks and outside via `editor.addComponents`.
I'd really appreciate a PR :)

**Comment by brandonburr86** [comment] 2017-11-22 22:51
okay I'll try that. What's a PR?

**Comment by brandonburr86** [comment] 2017-11-22 22:52
Okay I'll get that working and do a PR

**Comment by caholt** [comment] 2018-02-13 17:12
I am not sure if anyone still has this issue, but I experienced this issue and found that the problem  is caused by loading blank CSS.
So lets say we have a variable: 
`var LoadCSS = '';` 
and you call 
`editor.setStyle(LoadCSS);`
This will cause the columns not to display when you drag them to the canvas even though they are loaded when you look at the code.
The fix is simple, just do a check if the LoadCSS var actually has a value before using setStyle();

I hope this helps.

**Comment by artf** [comment] 2018-03-06 00:05
Should be fixed with latest versions of [grapesjs-blocks-basic](https://github.com/artf/grapesjs-blocks-basic/releases)

**Closed by artf** 2018-03-06 00:05 UTC
Labels: help wanted
