### ISSUE TITLE
How to add countdown/navigation event in undo/redo

### ISSUE THREAD

**Issue by Deepak813** [artf/grapesjs#1527] opened 2018-10-18 11:55 UTC
Hello @artf,

How can we add any changes/events in undo/redo Manager like when we drag element like navigation or countdown.
Hope for positive response
Thanks in advance

**Comment by artf** [comment] 2018-10-18 22:56
Duplicate of #1512
@Deepak813 more issues you open, later you get the response... so please avoid generating useless noise

**Closed by artf** 2018-10-18 22:56 UTC

**Comment by Deepak813** [comment] 2018-10-19 07:36
Hello @artf,

My bad.I forgot that i have already opened this issue.
I'll not repeat this thing.

Thankyou
