### ISSUE TITLE
[BUG] Highlight and toolbar positioned wrong on outside scroll

### ISSUE THREAD

**Issue by tomaskallup** [artf/grapesjs#2722] opened 2020-04-17 11:57 UTC
Are you using the latest release (older versions are NOT supported)? Yes
Are you facing the bug with your local copy of GrapesJS or with the current demo? Local
  - OS: Archlinux
  - Browser: Firefox 74.0 and Firefox developer edition 75.0b11
  - Grapes: v0.16.3

What is the expected behavior?
  - Highlight should update its position when the outside scrolls

What happens instead?
![grapes-scroll-issue](https://user-images.githubusercontent.com/26621166/79562540-91142180-80ab-11ea-9fc3-8107c94759c6.gif)

I did my best to try and replicate this behaviour, but couldn't. Even using the same stack (parcel, typescript, react, ant design) it seemed to work. So I would like some insight as to how I can debug this. 

Looking at the events in inspector, the scroll event is there.
![image](https://user-images.githubusercontent.com/26621166/79566113-49dd5f00-80b2-11ea-8445-8078caaa6e3b.png)
In my replication attempt (https://github.com/tomaskallup/grapesjs-react-scroll-issues) about the same styles should be applied (there is a flexbox which has scrolling content), but the issue isn't present there. (**UPDATE** Repo has been updated, issue is now present there, see https://github.com/artf/grapesjs/issues/2722#issuecomment-617154850)
If I switch the editor to fullscreen, it works perfectly.

**Comment by artf** [comment] 2020-04-21 12:04
Yeah really weird, my first guess was that canvas toolbars weren't updating on the window `scroll`, so I've tried to create a non-fullscreen example with a long page but I've realized that there is no `scroll` listener (on the main window) because is not necessary, toolbars are positioned correctly without that listener.
So, the only reasonable problems I can think about might be the Firefox browser (so try to see your page in Chrome, please) or maybe you're loading your page inside an iframe because that might be an issue, in that case, you would need to set up a `scroll` listener and propagate it to the editor

**Comment by tomaskallup** [comment] 2020-04-21 12:35
Hi, thanks for the reply!

Firefox doesn't seem to be the issue here (same behaviour in Chrome)
![image](https://user-images.githubusercontent.com/26621166/79864366-a655bc80-83d9-11ea-99f9-25349e219ab9.png)
Also the replication repo works in both browsers without the bug.

I'm not loading anything in iframe (this is inspector layout from the actual page)
![image](https://user-images.githubusercontent.com/26621166/79864693-2d0a9980-83da-11ea-912f-125ec5a1874a.png)
Only custom styles applied to the upper elements are some margins, paddings, min-height and max-width. Looking at it, the content seems pretty much same as in the replication repository, so I'm just getting more and more confused.

One thing I noticed, it "fixes" itself when resizing window (untill you scroll again)

**Comment by tomaskallup** [comment] 2020-04-21 12:42
@artf I think I found the cause, our root element `<div id="❤">` has this style:
```css
#❤ {
    height: 100vh;
    display: flex;
}
```

Adding that to the reproduction repo cause the issue to appear!

**Comment by tomaskallup** [comment] 2020-04-21 13:01
Alright, after even more investigation, it breaks even without the `flex`, because we still want to make the body not scroll, as the `<section class="ant-layout">` has to be the one scrolling (due to the sidebar).
A fix that comes to mind is a config option to select an element to which grapes would then bind the `scroll` listener, how does that sound?

**Comment by artf** [comment] 2020-04-28 11:55
Yeah probably adding an option like `listenToScroll` (as an array, to allow multiple elements) would be a good thing. As your case is quite common, I think it might also be useful adding the parent of the editor container element to the option (if is empty)

**Comment by mumumilk** [comment] 2020-08-27 18:56
I also managed to reproduce this bug in stackblitz if anyone wants to see it:

https://stackblitz.com/edit/js-3myvqp?file=index.js

Add any element and scroll down a little bit to see this behaviour:

![image](https://user-images.githubusercontent.com/21252014/91482993-5a31f180-e87d-11ea-8c62-d83fc07edb02.png)

i also noticed that if i remove the `overflow: auto` it prevents this bug from happening.

There is any known workaround for this?

**Comment by artf** [comment] 2020-08-28 19:26
It should be fixed in the next release

**Closed** 2020-08-28 19:58 UTC
Labels: help wanted

**Comment by siddhi1397** [comment] 2023-11-16 11:56
Hi @artf ,
One scenario where there are multiple containers of editor, then this misalignment is coming up after giving unique id to every editor container. Can you please help me if I am missing something out?
I have provided outer scroll body class to listenToEl and it's working when it's single editor.
