### ISSUE TITLE
[BUG]  redo undo doesn't work for components which has script

### ISSUE THREAD

**Issue by thinkanymore** [artf/grapesjs#1732] opened 2019-01-20 12:31 UTC
Like title says if the component has script attribute ，redo&&undo doesn't work ,undoManager add 1 to the stack ,the actions Array length less than 1, as shown in the figure.
I hope you can understand my description.
![components](https://user-images.githubusercontent.com/20251612/51439131-bf605100-1cf0-11e9-8a43-9de223c2d799.png)
![jsgenerator](https://user-images.githubusercontent.com/20251612/51439133-c4bd9b80-1cf0-11e9-9e9d-70ea73f90c46.png)
![managerundoredo](https://user-images.githubusercontent.com/20251612/51439245-52e65180-1cf2-11e9-9404-a5a72e586f22.png)

好运。。。

**Comment by artf** [comment] 2019-01-21 12:44
Hi @thinkanymore we have already an issue regarding the UndoManager #1512 (I close this so reply there if you need)
To be honest, I didn't get one thing, you're telling me the issue is with that `model.set('attributes', attr)`?! Can you tell me how did you end up with this conclusion?

**Closed by artf** 2019-01-21 12:44 UTC

**Comment by thinkanymore** [comment] 2019-01-21 14:05
I've got the wrong idea，there is a dead cycle,when the component has 'script' attribute trigger 'undo'
