### ISSUE TITLE
Image editor is not closed.

### ISSUE THREAD

**Issue by HarshOB** [artf/grapesjs#622] opened 2017-12-08 10:03 UTC
When I choose image component and don't choose an image for the first time then if I open image editor then It won't close after clicking on a close button.

**Comment by artf** [comment] 2017-12-08 15:17
@HarshOB I can't reproduce it (with the current demo). Are you able to provide a live demo?

**Comment by HarshOB** [comment] 2017-12-13 08:57
I'll provide a link to a live demo.

**Comment by artf** [comment] 2017-12-14 13:42
Ok I close this for now but will reopen once you provide a demo

**Closed by artf** 2017-12-14 13:42 UTC
Labels: can't reproduce
