### ISSUE TITLE
Asset manager

### ISSUE THREAD

**Issue by suraj740** [artf/grapesjs#497] opened 2017-11-08 19:15 UTC
hi @artf , 
is it possible to replace current asset manager , from my custom one?
I have created my own asset manager , i want to use that to upload images and all.
is it possible?

**Comment by artf** [comment] 2017-11-08 19:34
Duplicate of #491

**Closed by artf** 2017-11-08 19:34 UTC

**Comment by suraj740** [comment] 2017-11-08 19:45
Thanks @artf ,
But how can i call that custom asset manager directive inside target grapesjs which i was created.

if(editor) {
      editor.runCommand('open-assets', {
        target: "should i call my asset manage directive here"
        onSelect() {
          editor.Modal.close();
          editor.AssetManager.setTarget(null);
        }
      });
    }

**Comment by artf** [comment] 2017-11-08 20:00
no @suraj740 target is the component model, you should add your custom `open-assets` command
```js
editor.Commands.add('open-assets', {
     run(editor) {
          // here you call your custom manager
          // and you can get the selected component (target)
          // with editor.getSelected();
    }
})
```

**Comment by suraj740** [comment] 2017-11-08 20:04
Ok will try.
Thanks @artf .

**Comment by suraj740** [comment] 2017-11-09 13:32
@artf  can you help please, 
i am doing this to add my custom file manager.

editor.Commands.add('open-assets', {
     run(editor) {
              editor.runCommand('<file-manager></file-manager>', {
                   onSelect() {
                         editor.Modal.close();
                         editor.getSelected();
                   } 
             });
   }
});

**Comment by artf** [comment] 2017-11-09 21:21
```js
editor.Commands.add('open-assets', {
     run(editor) {
          // here you call YOUR CUSTOM MANAGER
          someCustomeManager.open({
                 onCustomSelect(url) {
                    // update the selected component
                    editor.getSelected().set('src', url);
                    ...
                 } 
          })
    }
})
```

**Comment by suraj740** [comment] 2017-11-10 09:29
@artf getting these errors, 
editor.Commands.add('open-assets', {
  run(editor) {
      getFileManager().open({
         onCustomSelect(url) {
          console.log('url', url);
        // update the selected component
       // editor.getSelected().set('src', url)
      }
   });
 }
});
![screenshot 2017-11-10 14 53 49](https://user-images.githubusercontent.com/24958883/32651573-752aa7a0-c627-11e7-8a25-c03fe68dc415.png)

**Comment by suraj740** [comment] 2017-11-15 09:51
Thanks @artf , i was able to replace current asset manager to custom one.
Thanks for giving that commands.

**Comment by suraj740** [comment] 2017-11-28 12:43
@artf  one more issue when using custom manager , what do we set on background images?
 editor.getSelected().set('src', url) not working on background images.
should i replace 'src' with 'background'?
