### ISSUE TITLE
How to make two text-boxes under the same label?

### ISSUE THREAD

**Issue by HarshOB** [artf/grapesjs#478] opened 2017-11-02 09:36 UTC
Hello,

Is it possible to make two TextBoxes under the same label? If it is possible then how can I create that?\

Thank You.

**Comment by artf** [comment] 2017-11-06 20:24
@HarshOB I don't understand where is the issue. Have you tried just to drag another input?

**Comment by HarshOB** [comment] 2017-11-09 12:44
Yes, I have tried but it won't work. Like I want two text boxes in front of one label like if as shown in below image I want to make two text boxes under the same label "TOKEN"
![screenshot from 2017-11-09 17-13-33](https://user-images.githubusercontent.com/28950214/32606056-d6b513ba-c579-11e7-8ceb-bf19d6730084.png)

**Comment by artf** [comment] 2017-11-09 21:14
Duplicate of #477

**Closed by artf** 2017-11-09 21:14 UTC
