### ISSUE TITLE
[QUESTION] Asset Manager - Upload Image

### ISSUE THREAD

**Issue by FrciSmrci** [artf/grapesjs#1218] opened 2018-06-19 12:49 UTC
Hey @artf ,

I have a question around Asset Manager. When uploading an image via computer or url the preview shows up at the asset collection in the modal, but after double clicking - selecting it the element in the canvas doesn't have a src. When opening the Asset Manager again after the upload and selecting the image everything works fine. 

What am I missing?

Thanks in advance.

**Comment by FrciSmrci** [comment] 2018-06-24 17:09
Hey @artf , the problem occurs only on newly uploaded pictures - which isn't possible to do in the demo. You can only select the ones that are already in the storage. :/

**Comment by artf** [comment] 2018-06-24 18:23
> the problem occurs only on newly uploaded pictures

I've tried to add it via url as you've suggested and it works as expected

>  After upgrading to the latest version from 0.14.15 the asset:add event isn't firing anymore.

Same, not able to reproduce it

**Comment by FrciSmrci** [comment] 2018-06-24 19:39
Hey @artf , I created an [example](https://stackblitz.com/edit/angular-kz951z) on Stackblitz (should probably do that before opening a ticket :/)  In the process of creating the example I discovered that the first issue of the image not rendering correctly lays inside my project. Regarding the second issue 
- event trigger on asset:add it still persist (example => app.component.ts => line 24).

Thanks in advance.

**Comment by artf** [comment] 2018-06-24 20:16
Just try to add the image via path and you'll see the event triggered
![schermata 2018-06-24 alle 22 15 35](https://user-images.githubusercontent.com/11614725/41823191-43493ae4-77fc-11e8-80ba-326e44e50057.png)

**Comment by artf** [comment] 2018-06-24 20:30
> adding the asset to canvas

What do you mean? Via drag and drop to the canvas?

**Comment by FrciSmrci** [comment] 2018-06-24 20:48
@artf I'm attaching the [video](https://drive.google.com/open?id=1xzrZZDOpUjLZf_du36bmcrq01kc36XXi) of the behaviour that is being skipped in the latest version of the library. But yeah, I misinterpreted the event trigger asset:add.

**Comment by artf** [comment] 2018-06-24 21:18
Ah ok you're talking about this https://github.com/artf/grapesjs/issues/1196 fixed now in https://github.com/artf/grapesjs/releases/tag/v0.14.21

**Closed** 2018-06-24 21:18 UTC

**Comment by FrciSmrci** [comment] 2018-06-25 08:43
@artf thank you. :)
