### ISSUE TITLE
is there  any plugins for adding shapes(Line, Oval ,Rectangle) in grapesjs 

### ISSUE THREAD

**Issue by himanshubudhlakoti** [artf/grapesjs#1523] opened 2018-10-17 05:10 UTC
Hello All,
please let me know 
**is there any plugins for adding shapes like Line, Rectangle oval at blockmanager**

**Comment by himanshubudhlakoti** [comment] 2018-10-17 09:18
please let me know its urgent

**Comment by v8jupiter** [comment] 2018-10-17 09:47
I have not seen such a plugin. But you can create you own, it not hard

**Comment by artf** [comment] 2018-10-18 23:12
Duplicate of #1517

**Closed by artf** 2018-10-18 23:12 UTC
