### ISSUE TITLE
BUG: Style Manager Background UI does not work correctly for Body/Wrapper

### ISSUE THREAD

**Issue by jlpatrick** [artf/grapesjs#3640] opened 2021-07-23 14:07 UTC
There is what appears to me to be a UI bug in the Style Manager's Background control when working with the Body vs the other components. This issue is visible in @kuhelbeher screenshot from #2834 , but I will provide some simple steps to reproduce as well. Perhaps this issue is related to that problem. 

1. Go to https://grapesjs.com/demo.html
2. Delete all the existing components until we just have the Body/wrapper
3. Select Body and set a background image (notice what the Background UI looks like at this point for the body image setting)
4. Open the blocks and drag a Navbar to the top of the page
5. Set a background image on the Navbar as well and it should render in the editor
6. Select the Body/wrapper again at this point and now look at the Background UI (it appears that it knows that a non-default setting has been made since the label has changed color and the reset icon is visible, but Layer 1 is NOT shown)
7. Select the Navbar in the editor and compare what it displays in the Background UI (Layer 1 is correctly shown)

### **Navbar selected**
![image](https://user-images.githubusercontent.com/38794168/126793473-0b78852e-3ef0-4c70-9736-06f6462da8ad.png)

### **Body selected**
![image](https://user-images.githubusercontent.com/38794168/126793512-05753b0b-24ec-41e4-8826-3040059e0499.png)

**Version:**
0.17.19

**Are you able to reproduce the bug from the demo?**

 - [X] Yes
 - [ ] No

**Comment by artf** [comment] 2021-08-02 17:20
Thanks Jim, yes it's actually the same issue, so I'm closing this one as a duplicate of #2834 
I'll post updates there once it's fixed.

**Closed by artf** 2021-08-02 17:20 UTC
