### ISSUE TITLE
Create and Edit Template into Database

### ISSUE THREAD

**Issue by mekamleshk** [artf/grapesjs#384] opened 2017-10-05 10:20 UTC
This is my code to Create a new template and insert the inline html with style into the database :

` <script type="text/javascript">
       var editor = grapesjs.init
           ({
              height: '100%',
              container : '#gjs',
              plugins: ['gjs-preset-newsletter'],
          storageManager: {
              id:'',
              type: 'remote',
              autosave: false,
              urlStore: '<?php base_url(); ?>/dragdropeditor/dragdrop/add',
              contentTypeJson: true,
              },
          });

          editor.Panels.addButton('options', [{
               id: 'save',
                    className: 'fa fa-floppy-o icon-blank',
                    command: function (editor, sender) {
                        if (sender)
                            sender.set('active', 0);
                          var html = editor.runCommand('gjs-get-inlined-html');
                          var storageManager = editor.StorageManager;
                          storageManager.store({"template-data":html})
                         // editor.store();
                          alert('Draft');

                        editor.on('storage:store', function (e) {
                          
                            console.log('CompleteHTML: ', html);
                        });
                    },

                    attributes: {title: 'Save Template'}
                }]);        
    </script>`

I am able to insert the template-data into database in this manner :

`created_at:"2017-10-05 12:13:09"

id:"114"

template-data:"'''<a class="paragraph" style="box-sizing: border-box;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</a>'''''"

template-name:"first_name"`

My edit template code :

` <script type="text/javascript">

var id = '<?php echo $this->uri->segment('3'); ?>';

     var editor = grapesjs.init
           ({
             height: '100%',
              container : '#gjs',
              plugins: ['gjs-preset-newsletter'],
          storageManager: {
              type: 'remote',
              autosave: false,
              urlStore: '<?php echo base_url(); ?>dragdropeditor/dragdrop/add',
              urlLoad: '<?php echo base_url(); ?>dragdropeditor/dragdrop/fetch/'+id,
              contentTypeJson: true,
              },
          });

          editor.Panels.addButton
          ('options',
            [{
              id: 'save-db',
              className: 'fa fa-floppy-o',
              command: 'save-db',
              attributes: {title: 'Draft'}
            }]
          );

        editor.Commands.add
        ('save-db',
        {
            run: function(editor, sender)
            {
              sender && sender.set('active'); // turn off the button
              editor.store();
              alert('Draft');    
            }
        });
    </script>`

Wonder why its not loading it into urlLoad

@artf  @sonnylloyd

**Comment by arthuralmeidap** [comment] 2017-10-05 11:59
@mekamleshk open the Developer Tools and see if the XHR is happening for the urlLoad and what is the response

**Comment by artf** [comment] 2017-10-05 12:00
Duplicate of https://github.com/artf/grapesjs-preset-newsletter/issues/17

**Closed by artf** 2017-10-05 12:00 UTC

**Comment by mekamleshk** [comment] 2017-10-05 12:05
I can see this 

`created_at:"2017-10-05 13:17:36"
id:"121"
template-data:"<h1 class="heading" style="box-sizing: border-box;">Insert title here</h1><table class="list-item" style="box-sizing: border-box;"><tr style="box-sizing: border-box;"><td class="list-item-cell" style="box-sizing: border-box;"><table class="list-item-content" style="box-sizing: border-box;"><tr class="list-item-row" style="box-sizing: border-box;"><td class="list-cell-left" style="box-sizing: border-box;"><img class="list-item-image" src="http://placehold.it/150x150/78c5d6/fff/" alt="Image" style="box-sizing: border-box;"></td><td class="list-cell-right" style="box-sizing: border-box;"><h1 class="card-title" style="box-sizing: border-box;">Title here↵                </h1><p class="card-text" style="box-sizing: border-box;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt↵                </p></td></tr></table></td></tr></table><table class="list-item" style="box-sizing: border-box;"><tr style="box-sizing: border-box;"><td class="list-item-cell" style="box-sizing: border-box;"><table class="list-item-content" style="box-sizing: border-box;"><tr class="list-item-row" style="box-sizing: border-box;"><td class="list-cell-left" style="box-sizing: border-box;"><img class="list-item-image" src="http://placehold.it/150x150/78c5d6/fff/" alt="Image" style="box-sizing: border-box;"></td><td class="list-cell-right" style="box-sizing: border-box;"><h1 class="card-title" style="box-sizing: border-box;">Title here↵                </h1><p class="card-text" style="box-sizing: border-box;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt↵                </p></td></tr></table></td></tr></table><div class="c1022" style="box-sizing: border-box; padding: 10px;">Insert your text here</div><p class="paragraph" style="box-sizing: border-box;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>"
template-name:"first_name"`

@arthuralmeidap

**Comment by arthuralmeidap** [comment] 2017-10-05 12:10
you need to return in the same format that is used to save.
So the same format that GrapesJS send to the remote when saving (urlStore) you should return when GrapesJS is loading the content (urlLoad)

**Comment by mekamleshk** [comment] 2017-10-05 12:36
Yes @arthuralmeidap 
 That's it's returning the same thing I stored in the database.
How should I load `var html = editor.runCommand('gjs-get-inlined-html');
                      var storageManager = editor.StorageManager;
                      storageManager.store({"template-data":html})`
