### ISSUE TITLE
BUG:  Ids gets changed while trying to set components on the canvas using json

### ISSUE THREAD

**Issue by shelendravashishtha2** [artf/grapesjs#4196] opened 2022-03-15 17:46 UTC
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome

### Reproducible demo link

no link

### Describe the bug

**How to reproduce the bug?**
1. ... use a demo json that can generate some component on the canvas, set an id in attributes 
2. ... use editor.setComponents(json)
3. ... set style using editor.setStyle() function for the same id element
**What is the expected behavior?**
... id shouldn't be changed while getting rendered on the canvas

**What is the current behavior?**
... id's are getting changed and because of which styles can't be implemented for the same

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment] 2022-03-24 13:22
Hi @shelendravashishtha2 can you please indicate the exact steps (I need to know what is the `json` you're referring to)

**Comment by JonathanRiche** [comment] 2022-03-25 17:43
I've seen this happen to if you don't save a reference to the CSS before using the editor.setComponents() method
All of the CSS markeup from the elements id selector/reference is removed when using editor.setComponents() method
The exact steps i've encountered are save a reference of the editor components as JSON ie

`let jsonElements = editor.getComponents().toJSON();

editor.setComponents(jsonElements)

`

after using the setComponents method the CSS makrup is lost for all of the id selectors of the blocks

The reason i've used saved the jsonElements is for having a way to edit them via the UI with an editor like monaco editor see my screenshot below, but even without modifying the JSON the CSS still get's reset

![image](https://user-images.githubusercontent.com/4421818/160173741-ea18353d-b9cc-4739-96e0-a8ed941a7494.png)

**Comment by JonathanRiche** [comment] 2022-03-25 19:49
I think I found the issue on my end using editor.getComponents().toJSON();

adds an empty "style":"" field to some of the components which is clearing out there CSS

ie
"components": [
            {
                "type": "box",
                "style": "",
                "attributes": {
                    "id": "ic7c"
                }
            },
            {
                "type": "box",
                "style": "",
                "attributes": {
                    "id": "if5j"
                }
            }
]

**Comment by shelendravashishtha2** [comment] 2022-03-26 13:24
> Hi @shelendravashishtha2 can you please indicate the exact steps (I need to know what is the `json` you're referring to)

Hi @artf ,
actually I am generating components json from a custom json of mine, there I'm providing ids to the components like this
attributes: { id: uuid1 },
and simultaneously creating css styles string for the same component, when json is completely built I'm using 
editor.setComponents() and
editor.setStyle() 
functions to render the components on my grapesJs canvas.
after following these steps relative html is getting generated but with some other ids and so my styles aren't getting applied to the html components.

**Comment by Ju99ernaut** [comment] 2022-04-04 08:55
> ie if it was #iefzr it will change to #iefzr-2

Also noticed this, when using the template manager plugin with `componentFirst: true`, on every load a `-2` gets added to all existing ids so in some cases I now have `some-id-2-2-2...`. Still investigating the issue so I'll provide more information if I have something conclusive.

**Comment by Ju99ernaut** [comment] 2022-04-04 16:16
I've set up a demo:
https://codepen.io/ju99ernaut/pen/ZEvvWPN

Steps to reproduce:
* Drag block onto canvas
* Select component and open style manager
* Add class and click sync
* Open code viewer(component should have a random id)
* Open console and run `editor.load()`
* Open code viewer(component should have a random id + `-2`)

**Comment by shelendravashishtha2** [comment] 2022-04-05 17:55
Hi Arthur,

try setting up given json by using setComponents function
[file.txt](https://github.com/artf/grapesjs/files/8420686/file.txt)

`editor.setComponents();`

And style using 
[style.txt](https://github.com/artf/grapesjs/files/8420701/style.txt)


`editor.setStyle()` function

expected scenario should be that the editor should render all the components on the canvas by applying related styles but in this case the component id's present in my json are different from id's generated on the canvas and that's why styles are not getting applied on the components

**Comment by artf** [comment] 2022-04-06 14:30
@shelendravashishtha2 By doing what you're suggesting and using your files I see no issue with IDs and styles are applied properly.
![Schermata 2022-04-06 alle 16 15 15](https://user-images.githubusercontent.com/11614725/161995798-fdacb28a-4043-41e5-a2c3-ffd3aac9cf6c.png)
Probably the only issue I see is using UUIDs for IDs without any prefix (in CSS, ID selector can't start with a number) which are escaped in this way
![Schermata 2022-04-06 alle 16 15 26](https://user-images.githubusercontent.com/11614725/161996701-1e58ed79-5989-4fe2-9fcb-b4f0521de4d4.png)

For now, I close this as there is no real reproducible demo if not the one provided by @Ju99ernaut but that one is referenced to the loading of the data containing existent IDs on the canvas (which can be prevented by clearing components manually before load).

**Closed by artf** 2022-04-06 14:30 UTC

**Comment by abozhinov** [comment] 2024-11-21 11:45
Hi,
I’m experiencing the same issue when duplicating a page. The new page ends up with different IDs.
