### ISSUE TITLE
Store the html and inline css in Editor.Store()

### ISSUE THREAD

**Issue by mekamleshk** [artf/grapesjs#382] opened 2017-10-05 05:44 UTC
I am trying to store the html and inline css , can you please in how to pass it to editor.store() function.
@artf

```js
editor.Commands.add`
        ('save-db',
        {
            run: function(editor, sender)
            {
              sender && sender.set('active'); // turn off the button
              var html = editor.runCommand('gjs-get-inlined-html');
              editor.store();
              alert('Draft');
              console.log(html);

              editor.on('storage:store', function(e) {
                    console.log('Stored ', e);
              });         
            }
        });
```

**Comment by sonnylloyd** [comment] 2017-10-05 07:58
@mekamleshk editor.store() function gets the **html, components, css, html and styles** and passes it to  **storage:store** event and you can access it like you have above

im sorry if i have miss understood what your asking but it looks like your trying to add a save button

the save button
```
editor.Panels.addButton('options', [{
               id: 'save',
                    className: 'fa fa-floppy-o icon-blank',
                    command: function (editor, sender) {
                        if (sender)
                            sender.set('active', false);
                        editor.store();
                    },
                    attributes: {title: 'save to database'}
                }]);
```

the store event

```
editor.on('storage:store', function (e) {
                console.log('STORE ', e);
                console.log('HTML', e.html);
                console.log('CSS', e.css);
            });
```

you can use grapejs's build in remote storage feature if you want to post these values to a backend

in the grapejs init you will want something like this

```
storageManager: {
                            type: 'remote',
                            urlStore: 'http://mywebsite.com/store/website',
                            contentTypeJson: true,
                        },
```
this will post a json string to the backend

**Comment by mekamleshk** [comment] 2017-10-05 09:08
Please recheck my code i have updated it. @sonnylloyd  @artf 
I want to store inline html

`var html = editor.runCommand('gjs-get-inlined-html');`

into mysql database using
`editor.store` function

**Comment by artf** [comment] 2017-10-05 11:55
duplicate of https://github.com/artf/grapesjs-preset-newsletter/issues/16

**Closed by artf** 2017-10-05 11:55 UTC
