### ISSUE TITLE
Implement TinyMCE and disable RTE

### ISSUE THREAD

**Issue by chiqui3d** [artf/grapesjs#1697] opened 2019-01-01 23:06 UTC
I'm trying to apply `tinyMCE `as a replacement for RTE, but I'm doing an impossible task, I'm following the same steps of the plugin CKEDITOR(https://github.com/artf/grapesjs-plugin-ckeditor) but without any result.

I have also thought about rewriting the text component, but it would be too much, since the text component is the default RTE.
I've created an example here https://jsfiddle.net/qept2v7r/3/ if you can help me, because the truth is I don't understand what's going on, and I have to click 3 times to get the editor toolbar out.

Thanks!

**Comment by chiqui3d** [comment] 2019-01-02 14:57
@artf
 I tried to do it in a different way, but it was impossible for me, I think it no longer loses focus, but I think the view is not updated, and I honestly don't understand :(
https://jsfiddle.net/5s80kxzm/4/

**Comment by artf** [comment] 2019-01-04 17:01
Hi @chiqui3d I'll try to check this out and will let you know

**Comment by artf** [comment] 2019-01-06 13:35
Unfortunately, due to this issue https://github.com/tinymce/tinymce/issues/4629, it's not possible to implement TinyMCE, indeed the wrapper of the grapesjs is inside another iframe and the formatting doesn't work (only undo/redo buttons work).

Here is my, almost complete, plugin example with tinyMCE:
https://jsfiddle.net/uq9hfL8p

I have to close this issue as the problem is related to tinyMCE

**Closed by artf** 2019-01-06 13:35 UTC

**Comment by adamyarger** [comment] 2019-06-13 14:59
@chiqui3d im a little late to the party, but I did get the cutomRte working with tinymce. In order for tinymce to work with iframe you have to pass in the context of the iframe window and document.

I added to the tinymce config in @artf example
```
content_window: document.querySelector('.gjs-frame').contentWindow,
content_document: document.querySelector('.gjs-frame').contentWindow.document,
```

https://jsfiddle.net/adamyarger/t3b5qky1/1/

**Comment by artf** [comment] 2019-06-13 22:52
@adamyarger 👏 great, definitely a step forward

BTW even with a `div` component, I'm still not able to use formats like alignment 🤔

**Comment by adamyarger** [comment] 2019-06-13 23:07
@artf im thinking it has to do with the menus being outside `.gjs-rte-toolbar`. Im currently playing around with `stopPropogation` to see if that fixes it.

**Comment by chiqui3d** [comment] 2019-06-14 08:04
@adamyarger 💯 Wow what big work, I hope you can work it out completely.

Thanks so much

**Comment by krishnaeverestengineering** [comment] 2020-07-14 14:44
> @chiqui3d im a little late to the party, but I did get the cutomRte working with tinymce. In order for tinymce to work with iframe you have to pass in the context of the iframe window and document.
> 
> I added to the tinymce config in @artf example
> 
> ```
> content_window: document.querySelector('.gjs-frame').contentWindow,
> content_document: document.querySelector('.gjs-frame').contentWindow.document,
> ```
> 
> https://jsfiddle.net/adamyarger/t3b5qky1/1/
> 
> Also note that some of the other formats are not working, this is due to the root tinymce element being a p tag. In order to use block elements in tinymce you'll have to enable div as a text component.

how to fix this?

**Comment by Abhisheknanda1344463** [comment] 2021-10-05 03:58
Hi  @adamyarger Any update?
I've tried with the ```stopPropogation```Alignment is still not working.

**Comment by krishnaeverestengineering** [comment] 2021-10-05 04:23
> Hi @adamyarger Any update? I've tried with the `stopPropogation`Alignment is still not working.

We have able to integrate tinymce differently @Abhisheknanda1344463

**Comment by krishnaeverestengineering** [comment] 2021-10-07 08:10
```
onRender: ({el}) ->
        tinymce = @gjsEditor.Canvas.getWindow().tinymce
        @rte_handler = new TinymceEditor.Initialiser(tinymce, config)
        @rte_handler.init(el, null, @onRTELoad.bind(this))

      onRTELoad: (editor) ->
        editor.on 'keyup', @setContent.bind(this)
        editor.on 'Change', @setContent.bind(this)

     setContent: (e) ->
        rte = @rte_handler.getRTE()
        @model.set('content', rte.getContent())
```

**Comment by GoodPHP** [comment] 2022-10-10 15:07
Hello, look on new RTE:
Tinymce 6 - https://gjs.market/products/tinymce-6-inline-text-editor
Froala - https://gjs.market/products/froala-inline-text-editor

**Comment by allphat** [comment] 2025-01-13 14:33
trying to maje it work too with tinymce7
it mostly works but i have problems with a js error
Uncaught TypeError: body is null  when trying to set hasTemporaryNode in tinymce source code

**Comment by mdmontesinos** [comment] 2026-02-05 16:11
Is there any free working solution for the TinyMCE integration? Because I've seen the Studio SDK plugin, but it doesn't work with GrapesJS.

**Comment by krishnaeverestengineering** [comment] 2026-02-06 10:44
> Is there any free working solution for the TinyMCE integration? Because I've seen the Studio SDK plugin, but it doesn't work with GrapesJS.

I have achieved via dedicated block and that block having tinymce config

**Comment by GoodPHP** [comment] 2026-02-09 20:42
I'm working on GrapesJS plugin to integrate my rte framework: https://github.com/GoodPHP/scribejs

It will be FREE plugin

**Comment by GoodPHP** [comment] 2026-02-11 16:37
Hi, just post new plugin RTE for grapesjs (free) : https://gjs.market/products/rte-scribejs-for-grapesjs-inline-toolbar
