### ISSUE TITLE
In Firefox, unable to drag components unto an empty canvas

### ISSUE THREAD

**Issue by roytang** [artf/grapesjs#116] opened 2017-06-21 08:59 UTC
Tried this in grapesjs.com/demo:
- click "Empty canvas" to empty the canvas
- try to drag any component from the blocks menu into the canvas, unable to drop them there

Above is working fine in IE/Chrome. My Firefox version is 54.0

**Comment by artf** [comment] 2017-06-21 12:13
Can't reproduce it (same versione). Do you have any error in console?

**Comment by roytang** [comment] 2017-06-21 13:44
No errors in the console.

You know how there's a green bar that shows you where you can drop the component? When this problem happens, there is no green bar at all no matter where I drag the component over the canvas. Releasing the mouse button loses the component icon on the cursor, but otherwise does nothing.

(There is also an "e is null" JS error in the console if I try to drag the component beyond the upper border of the browser window, but that doesnt seem relevant.)

**Comment by artf** [comment] 2017-06-21 21:23
Ok, I got the same behavior now (don't know why didn't get it in the last check). Seems like it's due to how differently `html` and `body` threaten in different render engines. Will try to fix it

**Comment by pournami17** [comment] 2017-07-17 05:35
Got the same issue. Any fixes?

**Comment by artf** [comment] 2017-07-17 19:26
At the moment is not possible as the fix I've tried (fill the height of html/body) breaks other stuff

**Comment by tribulant** [comment] 2017-07-20 10:14
Same problem in Safari as well but it is intermittent.
In most browsers, dropping blocks onto empty canvas doesn't work.

Ideally the Javascript could just check if the canvas is empty when dropping a block and then first put an empty DIV on the canvas to drop the block into maybe?

**Comment by bassouma21001** [comment] 2017-08-05 04:25
Same Problem also in Chrome  
Console alert (grapes.min.js:2 Invalid target position)

**Comment by artf** [comment] 2017-08-08 11:02
@tribulant @bassouma21001 I can't reproduce in either of them. Do you use the last version? Are you able to reproduce it in the demo?

**Comment by davellanedam** [comment] 2017-08-09 23:04
I can reproduce it in the demo, try to delete everything, then drag and drop any component and it breaks. The error message I got in the console is "Invalid target position: Target collection not found, Target is not droppable, accepts [undefined], Component not draggable, acceptable by [undefined]" The message also appears as an orange alert box at top right.

**Comment by danaketh** [comment] 2017-08-10 10:17
Same. With empty canvas you can't drag in anything. Once you have a single element in canvas, everything else seems to placed inside of it and there isn't a way of placing them outside. Like as if it needs some kind of wrapper element first.

**Comment by tribulant** [comment] 2017-08-10 10:30
@artf 

Same here, I can duplicate it locally as well as on the online demo.
As they said above, clear the canvas and try to drag an element onto the blank canvas.
Then you'll see the Javascript error in the browser's console.

**Comment by artf** [comment] 2017-08-10 12:07
@davellanedam @danaketh @tribulant thanks guys, can you also provide the browser and OS? On my side (mac, chrome 59) I have a similar issue but the reason it's completely different with the on from the Firefox. The error is popping out when you drop the component near to the edge of the wrapper (fixable) but it works otherwise, here the screencast:
![error](https://user-images.githubusercontent.com/11614725/29169638-485904dc-7dd5-11e7-9ea8-93d577964e32.gif)

**Comment by tribulant** [comment] 2017-08-10 12:13
@artf That is the problem I believe, the block just doesn't add to the canvas. See this video: https://goo.gl/RhsReH

**Comment by tribulant** [comment] 2017-08-10 12:13
Btw, I'm in Safari on macOS, not Firefox although I could reproduce it on Firefox. The problem doesn't seem to occur in Chrome though.

**Comment by artf** [comment] 2017-08-10 12:17
thanks @tribulant

**Comment by tribulant** [comment] 2017-08-10 12:19
@artf You're welcome and thanks for everything you do. It will be nice to be able to start with a blank canvas and build a webpage from the blank canvas. At the moment, it just doesn't seem possible.

**Comment by artf** [comment] 2017-08-10 12:34
@tribulant will do my best to fix it soon

**Comment by davellanedam** [comment] 2017-08-10 16:50
@artf Thanks to you! Using macOS, I usually test in all browsers, but it´s on Firefox 55 where the problem is.

**Comment by tribulant** [comment] 2017-08-10 17:58
@artf It happens to me in Safari on macOS. Cannot drag a block to an empty canvas. Nothing happens.

**Comment by danaketh** [comment] 2017-08-10 17:59
`Firefox 55.0 (64-bit)` on `Windows 10`. I worked my way around it by adding styled `<div>` into `#gjs` element and having that one stripped away on saving the output into `textarea` in the page form.

**Comment by artf** [comment] 2017-08-10 18:21
Would be great to hear someone else with macOS and Safari because I can't reproduce it.
@tribulant in the inspector, does the empty wrapper fill all the canvas?
![schermata 2017-08-10 alle 20 16 46](https://user-images.githubusercontent.com/11614725/29185415-712f5f30-7e09-11e7-975f-98614171d9ed.png)

**Comment by artf** [comment] 2017-08-15 08:09
Hi guys, I made a little update on this (v0.9.13, demo updated), besides the issue with edge corners you should be able to drag stuff in empty canvas even with Firefox (at least on my side it works now). Let me know

**Comment by davellanedam** [comment] 2017-08-16 16:26
Besides the issue with edge corners it´s working now on Firefox.

**Comment by oas** [comment] 2017-10-11 18:09
Hi @artf! I have the same problem, but not only in the corners. I tried the demo using Google Chrome (Version 61.0.3163.100) and Firefox (Version 61.0.3163.100).

Here is a short video:
[https://gfycat.com/OldRepentantBeaver](https://gfycat.com/OldRepentantBeaver)

Thank you in advance, great work! I hope this issue will be fixed so I can use this editor with my students!

**Comment by artf** [comment] 2017-10-11 19:28
Seems like there is an issue with input blocks, which also affect next drops. Should work properly with other blocks

**Comment by artf** [comment] 2017-10-20 13:16
The issue with edge corners should be fixed in the latest version https://github.com/artf/grapesjs/releases/tag/v0.12.15

**Closed by artf** 2017-10-20 13:16 UTC
Labels: bug
