### ISSUE TITLE
IE 11 issue

### ISSUE THREAD

**Issue by vmourya** [artf/grapesjs#337] opened 2017-09-26 11:50 UTC
Can not drop components on canvas in IE 11 but working fine in Firefox, Chrome.
While clicking on blocks to drag getting error in console: **Object doesn't support property or method 'matches'**
Also checked on http://grapesjs.com/demo.html getting same error.

TIA

**Comment by artf** [comment] 2017-09-26 12:58
Duplicate of #214

**Closed by artf** 2017-09-26 12:58 UTC

**Comment by ruelcena** [comment] 2017-10-03 01:54
Hey Guys, 
I don't this is fix but it works fine, here is what I do. Please have a look all matches error and replace this
`this.matches` that's it.
