### ISSUE TITLE
BUG: Textable attribute not working and causing exceptions 

### ISSUE THREAD

**Issue by hanna404** [artf/grapesjs#3243] opened 2021-01-20 21:19 UTC
**Version:**
0.16.27 to latest

**Are you able to reproduce the bug from the demo?**
Yes
[ X] Yes
[ ] No

**What is the expected behavior?**
insert text block inside another text block
*Describe the bug **detailed***

when adding new block, or even when creating a new custom type, the "textable attribute is not working as expected and as described. Nothing similar was reported before,
![image](https://user-images.githubusercontent.com/62241042/105239315-75c3ce80-5b75-11eb-9692-980eeef9b3a7.png)

![image](https://user-images.githubusercontent.com/62241042/105239511-82e0bd80-5b75-11eb-9714-ecdd7d5364b2.png)

**What is the current behavior?**
i am getting an error when dragging and dropping the element (as you can see the images attached,
I am trying on the demo locally ,
the added element is :
`		editor.BlockManager.add('my-text-test', {
  label: 'Simple map block',
  content: {
    type: 'text', 
    removable: true, 
	content:'test',    
    droppable: true,
    highlightable:1,
    copyable:true,
    draggable: 1,
    editable:1,
    textable: 1

  }
})`

let me know if further details are required i will be happy to share them,
thank you
*Descripe the bug **detailed***

**Are you able to attach screenshots, screencasts or a live demo?**

[ X] Yes (attach)
[ ] No

**Comment by artf** [comment] 2021-01-27 21:24
Duplicate of #2771

**Closed by artf** 2021-01-27 21:24 UTC
