### ISSUE TITLE
BUG: Can not delete background-image:url of body after an import

### ISSUE THREAD

**Issue by Light0815** [artf/grapesjs#3745] opened 2021-09-02 15:07 UTC
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chromev93

### Reproducible demo link

https://grapesjs.com/demo.html

### Describe the bug

**How to reproduce the bug?**
1. Import the following code

```
<style>* {
  box-sizing: border-box;
  }
  body {
    margin: 0;
  }
  *{
    box-sizing:border-box;
  }
  body{
    margin:0;
    background-image:url('./img/team3.jpg');
    background-repeat:repeat;
    background-position:left top;
    background-attachment:scroll;
    background-size:auto;
  }
</style>
```
2. Now try to delete the background-image: url
3. It is not possible

**What is the expected behavior?**
After clicking the body, opening the "open style manager" and then opening "Decorations", "Background" should indicate an layer with the image. Which should then be possible to be deleted.

**What is the current behavior?**
After clicking the body, opening the "open style manager" and then opening "Decorations", "Background" should indicate an layer with the image. It is not shown and therefore can not be deleted

If is necessary to execute some code in order to reproduce the bug, paste it here below:
No it's not

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment] 2021-09-08 11:38
Hi @Light0815 thanks for the report but I'm already aware of the bug with layers in conjunction with imported CSS, so I'm closing this one as a duplicate of #1396

**Closed by artf** 2021-09-08 11:38 UTC
