### ISSUE TITLE
Unwanted css after refreshing page

### ISSUE THREAD

**Issue by mandarinobellino** [artf/grapesjs#965] opened 2018-03-20 16:00 UTC
After integrating grapes to my platform a problem comes when, after refreshing the page, I click inside an elements : this one gets the style `border: 3px solid rgb(0, 0, 0);`
This issue goes on with every type of element I've insert in the canvas and it shows only on the first element I click after refreshing the page.

There is a specific way to interact with the update element style event? 

Here's a screencast of the problem -> https://screencast-o-matic.com/u/ja1e/problem

**Comment by artf** [comment] 2018-03-24 13:25
@mandarinobellino I can't reproduce it by using the official [demo](http://grapesjs.com/demo.html) (uses the latest version). Do you use the latest version? Are you able to reproduce a live demo?

**Comment by francesca-cicileo** [comment] 2018-03-29 20:26
I'm having the same issue, when using the grapesjs-preset-webpage plugin. Is there a CDN for that plugin so that I can create a demo on jsfiddle for you?

**Comment by artf** [comment] 2018-04-01 10:58
@francesca-cicileo you can use this one https://unpkg.com/grapesjs-preset-webpage

**Comment by francesca-cicileo** [comment] 2018-04-04 02:47
Hi @artf, I've reproduced the problem in a jsfiddle [here](https://jsfiddle.net/6awxo0jn/)

All I did was copy and paste the index.html file from the grapesjs-preset-webpage repo [here](https://github.com/artf/grapesjs-preset-webpage/blob/master/index.html). If you run the jsfiddle and then click on any element inside the pink box, that element will get a 3px white border around it.

**Comment by artf** [comment] 2018-04-15 12:38
Should be fixed with this one https://github.com/artf/grapesjs-preset-webpage/releases/tag/v0.1.10

**Closed by artf** 2018-04-15 12:38 UTC
Labels: can't reproduce
