### ISSUE TITLE
BUG: Cannot read properties of undefined (reading 'uploadFile') 

### ISSUE THREAD

**Issue by throne1986** [artf/grapesjs#3986] opened 2021-12-01 17:05 UTC
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Chrome v96.0.4664.45

### Reproducible demo link

https://codesandbox.io/s/react-redux-toolkit-application-forked-l5rhp?file=/src/pages/Editor.js

### Describe the bug

**How to reproduce the bug?**
1. Just drag and drop the logo to canvas you should get the error

![image](https://user-images.githubusercontent.com/27904724/144279499-e5c99a21-ab39-4090-ba6b-812c0da5d05a.png)

**What is the expected behavior?**
 Drag and drop the logo to canvas

**What is the current behavior?**
   I have created a simple custom plugin just a logo , now when I drag and drop to canvas I get the following error 
**_Cannot read properties of undefined (reading 'uploadFile')_**

If is necessary to execute some code in order to reproduce the bug, paste it here below:
```js
import React, { useState, useEffect } from "react";
import { useDispatch } from "react-redux";
import grapesjs from "grapesjs";
import block from "grapesjs-blocks-basic";

const Editor = () => {
  const [editor, setEditor] = useState();
  const dispatch = useDispatch();

  //custom logo plugin
  function pageLogo(editor) {
    editor.BlockManager.add("logo", {
      label: `<div className="gjs-block-label"><img src="https://i.ibb.co/nL2Q7WN/logo.png"></div>`,
      content: `<span><img src="https://i.ibb.co/nL2Q7WN/logo.png" /></span>`,
      category: {
        id: "logo",
        label: "Logo",
        open: true
      }
    });
  }

  useEffect(() => {
    const editor = grapesjs.init({
      container: "#editor",
      storageManager: false,
      blockManager: true,
      plugins: [pageLogo]
    });

    setEditor(editor);
  }, [dispatch]);

  return (
    <>
      <div className="ModalVideos"></div>
      <div id="editor"></div>
    </>
  );
};

export default Editor;
```
@artf  What am I doing wrong here?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by throne1986** [comment] 2021-12-02 11:11
@artf  I have tested with old versions below 22 everything is fine , but from version 25, 26, 27, 28, 29 there is this bug when u drag and drop a custom plugins which cotains an image , if you remove the image the error is gone , 

Please check this, thanks a lot brother

**Comment by jkntar** [comment] 2021-12-03 05:35
I ran into this problem, too. It seemed to happen whenever I started dragging a block's media icon instead of the block text or block container. It seems that the issue was resolved by adding `pointer-events: none;` to each of my block's media image styles.

The image I'm talking about being dragged:
![image](https://user-images.githubusercontent.com/75267836/144550654-469ca666-28a7-472d-b76e-c506f45f7935.png)

In my case: 
```javascript
editor.BlockManager.add('lx-button', {
    label: 'LiveX Button', 
    media: `<img style="width: 32px; height: 32px; filter: invert(0.75); pointer-events: none;" src='https://www.svgrepo.com/show/368574/button.svg' />`,
    category: 'LiveX',
    content: `
      <div class='lx-button normal'>View Details</div>
    `,
  })
```

**Comment by throne1986** [comment] 2021-12-03 09:10
> ```js
> pointer-events: none;
> ```

Agreed that resolve the issue @artf  is this the right aproach to this bug ?

**Comment by codingmachine16** [comment] 2021-12-06 17:42
Hi guys,
   I am also having the same issue. Please share the solution for it . Thanks

**Comment by throne1986** [comment] 2021-12-07 10:01
> Hi guys, I am also having the same issue. Please share the solution for it . Thanks

Hii, I added `pointer-events: none` to my custom plugins to solve the issue  but is this theright aproach? am not sure only @artf can confirm this

**Comment by markovic-nikola** [comment] 2021-12-08 14:45
`pointer-events: none;` is not working for me, I literally have to restart the whole browser in order to make it working normally again.

**Comment by artf** [comment] 2021-12-09 17:05
Yeah I'll actually fix that in the next release with the same approach https://github.com/artf/grapesjs/commit/828e64b235b835ce5a42d50ee8565e9f4da7839a

**Closed by artf** 2021-12-09 17:05 UTC

**Comment by luasenvy** [comment] 2021-12-17 07:24
is there no one solve the other way?

i'm using nuxt(2.15.8) with grapesjs(0.17.29).

i follow this issue comments:
```
<style scoped lang="scss">
::v-deep .gjs-block {
  &__media,
  &-label {
    pointer-events: none;
  }
}
</style>
```

![image](https://user-images.githubusercontent.com/24634713/146505126-505c2a1f-da2b-46be-b19e-a9802b92697d.png)

```html
<div class="gjs-blocks-c" style="">
  <div
    label='
            <div class="d-flex flex-column flex-grow-1 gjs-block-label">
              <i class="gjs-block-icon fas fa-code fa-3x"></i>
              <div class="mt-auto">사용자정의</div>
            </div>
          '
    content="[object Object]"
    media=""
    category="[object Object]"
    activate="true"
    select="true"
    resetid="false"
    disable="false"
    attributes="[object Object]"
    id="custom-code"
    render="function () { [native code] }"
    cid="c33"
    collection="[object Object]"
    _changing="false"
    _previousattributes="[object Object]"
    changed="[object Object]"
    _pending="false"
    _events="[object Object]"
    _listenid="l179"
    _listeners="[object Object]"
    class="gjs-block gjs-one-bg gjs-four-color-h"
    title="사용자정의"
    draggable="true"
  >
    <div class="d-flex flex-column flex-grow-1 gjs-block-label">
      <i class="gjs-block-icon fas fa-code fa-3x"></i>
      <div class="mt-auto">사용자정의</div>
    </div>
  </div>
</div>
```

![image](https://user-images.githubusercontent.com/24634713/146505621-3814af68-ff53-48f2-96b7-854e47ceaff1.png)

![image](https://user-images.githubusercontent.com/24634713/146505357-c0f6c328-5195-45fd-a2a1-60ac1037c8dc.png)


The bug still occurs. I don't even use images on label.

**Comment by luasenvy** [comment] 2021-12-17 07:34
> `pointer-events: none;` is not working for me, I literally have to restart the whole browser in order to make it working normally again.

@markovic-nikola  This Is REALLY IMPORTANT. SUPER THANKS. :D

**Comment by MarksEliel** [comment] 2022-01-03 18:49
I have the same problem https://prnt.sc/25uumtx

**Comment by luasenvy** [comment] 2022-01-06 02:48
> I have the same problem https://prnt.sc/25uumtx

In my case, reinstall grapesjs to 0.17.29
And,  referenced [This comment](https://github.com/artf/grapesjs/issues/3986#issuecomment-988876735)

**Comment by skru** [comment] 2022-01-11 10:35
A rare use-case I know, but the pointer-events fix will not stop the bug if a user drags an image from their OS into the canvas. 

I've just had to downgrade for now but this shouldn't be closed

**Comment by artf** [comment] 2022-01-18 14:22
@skru there were actually more than one problem in this bug and the one you're mentioning was actually fixed [here](https://github.com/artf/grapesjs/pull/3934/files)

**Comment by omergr8** [comment] 2022-02-03 16:04
@artf  I am still facing this issue. Getting same error whenever I tried to drag and drop image from my pc to canvas. Is there any temporary fix for this yet?

**Comment by artf** [comment] 2022-02-05 20:28
@omergr8 I see no issues on the official demo, so if you believe the problem is still there, please open a new issue with a reproducible demo.

**Comment by luasenvy** [comment] 2022-02-06 03:40
> @artf I am still facing this issue. Getting same error whenever I tried to drag and drop image from my pc to canvas. Is there any temporary fix for this yet?

I think it's the same situation I've been through

> literally have to restart the whole browser

What I wanted to emphasize is this.
Even if you change the version, didn't solve it.

In my case,
It was an ignorant way
I restarted chrome every time I lowered the dependencies one by one. and i find working version. ( in current version of greapesjs. there is no need to consider )

so, I think this issue is related to not only CSS, but also browser functionality.
the point here is, I restart whole chome process including the Chrome App.

literally whole browser. as @markovic-nikola said

how about try to install `grapesjs` latest version( now 0.18.2 ), clear page cache and restart chrome process?

Of course, you must have rebooted in the meantime.
If the error is the same, I think you need a different approach. :thinking:

**Comment by artf** [comment] 2022-02-06 04:48
@luasenvy this is why I always ask for a reproducible demo because people do not realize they're running behind a cached file
