### ISSUE TITLE
BUG: Editing button text doesn't work correctly

### ISSUE THREAD

**Issue by tudor-ooo** [artf/grapesjs#3464] opened 2021-05-19 13:15 UTC
## Description
- 0 - Visit: https://grapesjs.com/demo.html
- 1 - Select button:
<img width="674" alt="Screenshot 2021-05-19 at 15 09 53" src="https://user-images.githubusercontent.com/668451/118818468-a5c97700-b8b4-11eb-9006-56abe37a8343.png">

- 2 - Change content:
<img width="253" alt="Screenshot 2021-05-19 at 15 10 05" src="https://user-images.githubusercontent.com/668451/118818505-afeb7580-b8b4-11eb-8369-26d4939cae1a.png">

- **3 - Refresh the page**

- 4 - Result:
<img width="665" alt="Screenshot 2021-05-19 at 15 10 19" src="https://user-images.githubusercontent.com/668451/118818568-c09beb80-b8b4-11eb-93d1-99dc1d5e27c2.png">

^
We have "HelloSend" instead of "Hello"

**Comment by artf** [comment] 2021-05-22 16:40
Duplicate of #3205

**Closed by artf** 2021-05-22 16:40 UTC
