### ISSUE TITLE
editor.setComponents auto generate unwanted css

### ISSUE THREAD

**Issue by richieteh94** [artf/grapesjs#488] opened 2017-11-07 09:30 UTC
I'm used the html and css editor that mention in #324 .
After I edited the html and css it will generate a CSS where I suspect caused by editor.setComponents()
Not sure this is a bug or normal behavior.

grapesjs version - 0.12.8
grapesjs preset - gjs-preset-newsletter 0.2.15

**Comment by artf** [comment] 2017-11-07 12:56
First of all, update your grapesjs version, then be more specific about your changes. What did you change? What do you mean with *unwanted css*?

**Comment by richieteh94** [comment] 2017-11-08 03:37
Hi, I updated my grapesjs to v0.12.25
Scenario : 
I pull a section into the drop area and the image shows the code.
I did not change any code inside the area.
After I press the EditCode Button it will chop down the CSS from the original and add into the existing CSS (this makes duplicate of style that causes the normal change of margin or padding unable take effect).
Before press Edit Code button:
![grapesjsbeforeedit](https://user-images.githubusercontent.com/26899725/32530245-ed3466ac-c477-11e7-89ba-65332e996a4f.PNG)
After press Edit Code button:
![grapesjsafteredit](https://user-images.githubusercontent.com/26899725/32530239-ea54ea24-c477-11e7-9405-e1b5e93f1156.PNG)

**Comment by artf** [comment] 2017-11-08 19:57
That explosion of style rules is due to the browser's CSS parser and I can't do much about until there will be a possibility to attach custom CSS parsers. Not sure if it's the `duplicate of style` you were talking about

**Comment by richieteh94** [comment] 2017-11-09 03:49
thanks @artf I will try to find a solution for it and update here if any solution appears.

**Comment by thecodefish** [comment] 2017-11-13 02:25
In my use case I am constantly getting & setting the html/css inside the editor, and what I found is that it would end up duplicating the 'default' styles (see the * and body styles in the image above - they appear twice).

I managed to solve that by making sure to clear the css before I (re)set it - something like the following:

``` js
editor.CssComposer.getAll().reset();
editor.setComponents(components);
editor.setStyle(css);
```

**Comment by richieteh94** [comment] 2017-11-13 08:26
@thecodefish thank you for the solution.
you saved my day. :)

**Comment by chiqui3d** [comment] 2018-01-27 13:35
@thecodefish , Exactly where should I add the code to fix the duplication of style?

**Comment by thecodefish** [comment] 2018-01-29 20:25
@chiqui3d I think whenever you need to modify the css from some external source, you'll probably want to reset the css composer first. So if you have something like `editor.setStyle(css);` in your code, you may need to call `editor.CssComposer.getAll().reset();` first.

**Closed** 2018-04-15 12:51 UTC
