### ISSUE TITLE
Problem with Box/Row Class

### ISSUE THREAD

**Issue by fzs1994** [artf/grapesjs#132] opened 2017-06-30 03:45 UTC
Screenshots below:

In live editor i.e. on website:
![screenshot from 2017-06-30 09-13-17](https://user-images.githubusercontent.com/10684213/27720045-a4732440-5d74-11e7-9e97-84c3d915a1af.png)

After exporting into HTML and CSS: 
![screencapture-file-home-software-desktop-index-local-template-html-1498794071019](https://user-images.githubusercontent.com/10684213/27720046-abddc30c-5d74-11e7-9496-5d654658d80c.png)

**Edit:** Maybe its problem with 3/7 box.

**Comment by artf** [comment] 2017-06-30 18:42
thanks @fzs1994, I think the problem is the same as #131 will fix it for the next release.
I close this as a duplicate

**Closed by artf** 2017-06-30 18:42 UTC
