### ISSUE TITLE
image reverted to original size after resized

### ISSUE THREAD

**Issue by theanhmx** [artf/grapesjs#738] opened 2018-01-10 10:00 UTC
hi, i got a strange issue with component:
i got 2 types, image and icon
```js
domComponents.addType('icon', {
  model: imageModel.extend({
    defaults: Object.assign({}, imageModel.prototype.defaults, {
      traits: [{
        type: 'text',
        label: 'icon URL',
        name: 'src',
        changeProp: 1
      }],
      removable: false,
      draggable: false,
      droppable: false,
      badgable: false,
      stylable: false,
      highlightable: true,
      copyable: false,
      resizable: false,
      editable: true,
      selectable: true
    })
  }, {
    isComponent: function(el) {
      if (el.getAttribute !== undefined && el.getAttribute('deletable') == '0' && el.tagName == 'IMG') {
        return {
          type: 'icon'
        };
      }
    }
  }),
  view: imageView.extend({
    initialize: function() {
      var defaultClickEventHandler = this.events.click || function() {};
      var defaultDblClickEventHandler = this.events.dblclick || function() {};
      defaultView.prototype.initialize.apply(this, arguments);
      this.events.dblclick = function() {
        console.log('dblclick');
      };
    }
  }),
  onValueChange: function() {
    this.target.set('src', this.model.get('value'));
  }
});

domComponents.addType('image', {
  model: imageModel.extend({
    defaults: Object.assign({}, imageModel.prototype.defaults, {
      traits: [{
        type: 'text',
        label: 'Image URL',
        name: 'src',
        changeProp: 1
      }]
    })
  }, {
    isComponent: function(el) {
      if (el.tagName == 'IMG') {
        return {
          type: 'image'
        };
      }
    }
  }),
  view: imageView,
  onValueChange: function() {
    this.target.set('src', this.model.get('value'));
  }
});
```
the issue is when i first drag and drop the image component, i'm able to resize and save it,
but when i load the template again, i'm not able to resize the image again.
i can adjust the image size but after couple of second it will be reverted.
i noticed there are component:update and component:styleUpdate event fired.
is this have anything to do with the angularjs digest cycle?
i'm using with angular 1.3

**Comment by artf** [comment] 2018-01-10 21:57
Are you sure there are no strange styles loaded which forces img style? Try to inspect and see if style actually changes

**Comment by theanhmx** [comment] 2018-01-11 03:01
yes, i can see it change in the local storage.
but after some short time it changed back

**Comment by artf** [comment] 2018-01-11 13:05
Are you able to reproduce it with a live example?

**Comment by theanhmx** [comment] 2018-01-12 07:00
@artf , thanks a lot for your help.
but i could not reproduce it in other env, only able to give you pieces of codes.
this is the module, we using it with angular, if you can have a look

[templateBuilder.zip](https://github.com/artf/grapesjs/files/1625156/templateBuilder.zip)

**Comment by artf** [comment] 2018-01-13 12:56
Apologize @theanhmx but if you're not able to reproduce it, probably this means it's something wrong in **your** application, try to isolate the editor from the angular to verify if this is somehow related to the issue.
I close this for now, but for anyone else facing the same issue please try to create a live demo first and I'll reopen it

**Closed by artf** 2018-01-13 12:56 UTC
