### ISSUE TITLE
Update styleManager properties on drag and resize

### ISSUE THREAD

**Issue by alemenciones** [artf/grapesjs#2447] opened 2019-12-09 19:02 UTC
I need to see in real time the update of the properties of the component in the styleManager when I drag or resize a component (or in some other way that changes its style properties).

I've managed to see width and height running this:

`editor.on("styleManager:change:width styleManager:change:height", (response) => {
editor.trigger("component:styleUpdate");
});`

Now, i need something like this to see the component position (top, bottom, left, right) and the font-size (then maybe something else), i'm tried other things like `editor.trigger("component:toggled");` and `StyleManager.render(),` but it's not the way...

Any suggestions?

**Comment by artf** [comment] 2019-12-09 23:12
Duplicate of #2374

**Closed by artf** 2019-12-09 23:12 UTC
