### ISSUE TITLE
Question: Dragging blocks into a Text block? 

### ISSUE THREAD

**Issue by mathieuk** [artf/grapesjs#481] opened 2017-11-03 07:47 UTC
This is not a bug but an implementation question. If this is not the right place to ask these questions, please let me know. 

We're working on an implementation where we want to use GrapesJS to allow users to create an e-mail template. As part of this implementation we are working to create mail-merge functionality: we've introduced the concept op 'merge-fields' or 'placeholders' which we will replace with the proper values on the server side. This means we send over the `components` JSON structure and turn it into HTML server-side, replacing values as we go.

So, as an example, one of our users might enter the _text_:  `Hello <<username>>` and we'll replace that merge-field `<<username>>` with the proper field.

But, we haven't been able to implement this this way quite yet as we're not able to drag these blocks into a Text block. We can only drag it around it. So, for now we're extending the RTE with a merge-field 'inline block' ( `<input type=text readonly class=mergeField data-isMergefield=1 />`) and creating a merge-field block with the same HTML in the block manager. Implementing a DomComponent type to recognize it offers a method to configure it. But it feels suboptimal, we'd really like to be able to drag that mergefield block onto the right place in the textfield. 

To allow this, I imagine GrapesJS would have to be able to grab the textNode and split it in to (atleast) two textnodes and a tag for the merge-field but I'm not sure where to start with this. Could you advise as to how we might implement this?

**Comment by mathieuk** [comment] 2017-11-03 07:48
I suspect #287 is actually the same question.

**Comment by artf** [comment] 2017-11-06 20:50
Have you checked [API-Rich-Text-Editor](https://github.com/artf/grapesjs/wiki/API-Rich-Text-Editor)? You can add a custom action like this
```js
editor.RichTextEditor.add('custom-vars', {
  icon: `<select class="gjs-field">
		<option value="">- Select -</option>
        <option value="[[firstname]]">FirstName</option>
        <option value="[[lastname]]">LastName</option>
        <option value="[[age]]">Age</option>
      </select>`,
    // Bind the 'result' on 'change' listener
  event: 'change',
  result: (rte, action) => rte.insertHTML(action.btn.firstChild.value),
  // Reset the select on change
  update: (rte, action) => { action.btn.firstChild.value = "";}
})
```
![rte-action](https://user-images.githubusercontent.com/11614725/32463242-810de0fc-c33c-11e7-81df-3524c0ad55ac.gif)

**Comment by mathieuk** [comment] 2017-11-08 08:30
Yes, I've used that and I've pretty much got that working. The difference is that I am not using a text placeholder like you are. I'm actually inserting a block (with a corresponding 'type') so that I can further configure these placeholders (for instance, a field might be a Datetime field and my user may want to configure the exact output format for that datetime). I used HTML5 drag'n'drop to implement this and that works pretty nice, bút...

It feels like departing from the expected user interface. I feel I should be able to drag a mergefield from the 'blocks' and onto the right position. I've been toying around with the Sorter to allow this and I'm up to this:

![image](http://g.recordit.co/ept73MqtM8.gif)

I now have the problem that the Sorter very much wants actual blocks to align to so I have some more tweaking to do.  For now implementing this has required changed in the ComponentTextView (mostly: dont clear out the toolbar for 'mergefields') and the Sorter (if I'm hovering a mergefield over a textblock, insert HTML into the activeRTE instead of appending a block).

I'm currently working on making the dragging work more reliably (for some reason, whenever I drag _right_ the field gets appended to the textnode instead of at the cursor position, works fine when dragging _left_ :) ), making the sorter ignore the idea of 'blocks' when within a textfield, showing the proper placeholder in that case (I'd want to see the actual cursor) and cleaning things up.

Not sure on how to approach the Sorter issue at this point, short of specialcasing textblocks so if you have any ideas in that area I'd love to hear them. You can see some of the hacky code I've made so far over at https://github.com/mathieuk/grapesjs/commit/d58c5ee5306c358cd19509f6b8affe9bb60493ed .

**Comment by artf** [comment] 2017-11-08 13:51
Well @mathieuk I've never taken into account the possibility to add stuff inside a text component, mainly because it might lead strange behaviors (probably even from UX), but it is definitely an interesting proposal. About your Sorter question, I'd suggest creating a new property for blocks, eg.
```js
blockManager.add('my-block', {
     label: 'Block',
     textable: 1, // allow the block to be inserted inside text components
     content: `...`,
})
```
and differentiate the sorter's behavior by this property

**Comment by mathieuk** [comment] 2017-11-18 15:52
@artf so, I've taken your advice and went that route and i now have a fairly functional situation where it lets you drag a mergefield onto a textview, lets you move it around and lets you move it between textviews and other blocks. 

![image](http://g.recordit.co/jxaooLomZT.gif)

You can see my implementation over at https://github.com/mathieuk/grapesjs/tree/mergefields/src .  
Would you be interested in having this in core? Would you need any additional changes for that?

**Comment by artf** [comment] 2017-11-21 13:59
Wow @mathieuk, this is amazing 😍  it'd awesome to have it in core

**Comment by mathieuk** [comment] 2017-11-21 16:15
@artf Great! Any ideas on what form that should take? The merge fields approach that I'm using _is_ kinda specific to our solution where we process the JSON generated by GrapesJS server-side. Any suggestions as to what type of sample block we should add to be draggable onto the textfield by default?

**Comment by NorthstarTech** [comment] 2017-11-22 10:47
I go through with your code @matthieuk , but its not working properly. It doesnot allow to add inside the text. It always drag on a separate textfield. 
Need your help asap. Thanks.

**Comment by kickbk** [comment] 2017-11-25 01:38
Hmm, exactly what we need as well. Would love to see such functionality merged into the core, but would be great if it was not limited to just the mjml preset.

**Comment by artf** [comment] 2017-11-28 12:59
@mathieuk can I just use any block content? I mean something like this:
```js
blockManager.add('my-block', {
     label: 'Block',
     textable: 1, 
     content: `<div style="...">custom stuff / custom components</div>`,
})
```
I don't care about the`content`, I know that with `textable` I'm able to drag it inside text components.
Would be awesome if you set up a demo just to test it online :) (with something like codepan/codesandbox)

**Comment by gordon-matt** [comment] 2018-01-19 03:33
@mathieuk / @artf   I'm desperate for this functionality right now as well. Any idea when this will be merged to core?

**Comment by artf** [comment] 2018-01-19 12:42
I hope to hear more from @mathieuk about this :)

**Comment by kickbk** [comment] 2018-01-25 19:50
For those looking for a ckeditor 4 merge fields plugin, this works: https://github.com/57u
To activate:

```
'gjs-plugin-ckeditor': {
	options: {
		...
		extraPlugins: '...,strinsert',
		toolbar: [
			...
			{name: 'Merge Fields', items: [ 'strinsert' ]},
		],
		strinsert_strings: [
			{'value': '*|FIRSTNAME|*', 'name': 'First name'},
			{'value': '*|LASTNAME|*', 'name': 'Last name'},
			{'value': '*|INVITEURL|*', 'name': 'Activate invite URL'},
		],
		// Optionally add the below settings
		strinsert_button_label: 'Merge Fields',
		strinsert_button_title: 'Insert Merge Field',
		...
	}
},
```

**Comment by tvkit** [comment] 2018-02-27 22:21
Any progress on this cool capability, @mathieuk ?

**Comment by LKozakewycz** [comment] 2018-07-20 14:16
@mathieuk @artf 

I'm looking at using the textable method and have built grapesjs with your implementation but I'm still struggling to get the component to drop into the middle of the RTE. Was there something specific you did to get this to work?

**Comment by mathieuk** [comment] 2018-07-24 06:05
I haven't had the time to work on this any further yet, sorry @artf. I might later this year. @LKozakewycz I'm a bit rusty on the details, but I recall that having to set ContentEditable was crucial to getting accurate ranges from the textselection APIs in the various browsers. That is: the textblock must be in content-editable mode during the whole time you're dragging the mergefield over it. That was one of the challenges of getting it right..

**Comment by LKozakewycz** [comment] 2018-07-24 08:44
@mathieuk - I've been working on it lately and have so far come up with this, very similar to yours:

![ezgif-1-307632a1f2](https://user-images.githubusercontent.com/4478123/43126772-949aed58-8f25-11e8-897c-24e96f45d3d4.gif)

I know for a fact that setting `contenteditable="false"` on the merge field component itself will let the RTE know it is to be handled as a whole block, because unfortunatly at this moment the RTE will see it as just more editable text (i.e, you can edit the text inside the component). By doing this, you can use backspace to delete the merge field as a whole. 

The trick is... trying to set `contenteditable` as a permanent attribute. I don't know if it's the RTE activation, but I'm working out how to get `contenteditable` to stick.

**Comment by LKozakewycz** [comment] 2018-07-24 09:42
Found it. Set `contenteditable` attribute on the component to `false` and ensure the attribute is not skipped over if explicitly set.

ParserHtml.js
```javascript
//...
          } else if (nodeName == 'contenteditable') {
            // Explicitly set contenteditable attributes should not be ignored
            if ( nodeValue === 'false' && !model.editable ) {
              model.attributes[nodeName] = 'false';
            }
            continue;
          }
//...
```

I'll be doing some more work on this and hopefully share in the future.

**Comment by artf** [comment] 2018-07-25 21:13
Thanks for the help @LKozakewycz looking forward to your updates. BTW, before applying your changes I'd like to understand why `contenteditable` is removed when parsed, honestly, I'd expect to see it kept

**Comment by LKozakewycz** [comment] 2018-07-26 08:18
@artf In this case, `contenteditable` is set to `false` on the merge field only because it let's the merge field show as a single block and not a bunch of characters. It stops the cursor from accessing the contents of the merge field block and allows for deleting it entirely using backspace. 

In my version, I intend to use modals to display an advanced merge field selector which can be populated by meta data in my back-end. One of the challenges with this is trying to understand why the modal doesn't appear automatically when I drop it in the canvas (just like the image block).

**Comment by chris-robbins** [comment] 2019-02-04 19:53
@artf When applying this method for merge tags, the options drop down is duplicated when leaving and re-entering the editor. I assume it is caching the command and adding the custom-vars icon everytime, can you explain how to avoid this? 
![screen shot 2019-02-04 at 1 51 00 pm](https://user-images.githubusercontent.com/37622931/52233264-3dd9f880-2884-11e9-8bec-455eec868a2b.png)

**Comment by artf** [comment] 2019-02-06 23:33
@chris-robbins it works fine, by trying my old snippet, so be sure not adding that action every time you "re-enter the editor"

**Comment by artf** [comment] 2019-04-09 22:15
Probably in the next release, this feature will be available.
![textable](https://user-images.githubusercontent.com/11614725/55838123-a8791000-5b23-11e9-8866-c2059a972fc5.gif)

So `textable` will be just another property, this will allow any component to be dropped inside Text components.
Here is the code of the component from the example above:
```js
// Define a component with `textable` property
editor.DomComponents.addType('var-placeholder', {
      model: {
        defaults: {
          textable: 1,
          placeholder: 'VARIABLE-1',
        },
        toHTML() {
          return `{{ ${this.get('placeholder')} }}`;
        },
      },
	  // The view below it's just an example of creating a different UX
      view: {
        tagName: 'span',
        events: {
          'change': 'updatePlh',
        },
        // Update the model once the select is changed
        updatePlh(ev) {
          this.model.set({ placeholder: ev.target.value });
          this.updateProps();
        },
        // When we blur from a TextComponent, all its children components are
        // flattened via innerHTML and parsed by the editor. So to keep the state
        // of our props in sync with the model so we need to expose props in the HTML
        updateProps() {
          const { el, model } = this;
          el.setAttribute('data-gjs-placeholder',  model.get('placeholder'));
        },
        onRender() {
          const { model, el } = this;
          const currentPlh = model.get('placeholder');
          const select = document.createElement('select');
          const options = [ 'VARIABLE-1', 'VARIABLE-2', 'VARIABLE-3' ];
          select.innerHTML = options.map(item => `<option value="${item}" ${item === currentPlh ? 'selected' : ''}>
			${item}
		  </option>`).join('');
          while (el.firstChild) el.removeChild(el.firstChild);
          el.appendChild(select);
          select.setAttribute('style', 'padding: 5px; border-radius: 3px; border: none; -webkit-appearance: none;');
          this.updateProps();
        },
      }
    });
	
	// Use the component in blocks
    editor.BlockManager.add('simple-block', {
      label: 'Textable block',
      content: { type: 'var-placeholder' },
    });
```

**Comment by dazakorn** [comment] 2019-04-15 20:35
Hello @artf, I'm using the source code to add var-placeholder but it does not work, should I do something extra in the editor so that the text allows to add the object var-placeholder between lines? In my case it is only added to the beginning or end of the text.

**Comment by BlazedCode** [comment] 2019-04-16 08:50
Thanks @artf for all your hard work, really appreciate. I'll give this a try.

**Comment by artf** [comment] 2019-05-01 23:39
Now available https://github.com/artf/grapesjs/releases/tag/v0.14.61

**Closed by artf** 2019-05-01 23:39 UTC

**Comment by HelveticaScenario** [comment] 2019-05-11 00:07
> @artf When applying this method for merge tags, the options drop down is duplicated when leaving and re-entering the editor. I assume it is caching the command and adding the custom-vars icon everytime, can you explain how to avoid this?
> ![screen shot 2019-02-04 at 1 51 00 pm](https://user-images.githubusercontent.com/37622931/52233264-3dd9f880-2884-11e9-8bec-455eec868a2b.png)

I've had this problem too, I think it has something to do with the rte being global under the hood. try adding it in this initialization object for the grapesjs instance, with something like this
```
grapesjs.init({
  //...
  richTextEditor: {
    actions: [
      'bold',
      'italic',
      'underline',
      'strikethrough',
      'link',
      {
        name: 'custom-vars',
        icon: `<select class="gjs-field">
                <option value="">- Select -</option>
                <option value="[[firstname]]">FirstName</option>
                <option value="[[lastname]]">LastName</option>
                <option value="[[age]]">Age</option>
              </select>`,
        // Bind the 'result' on 'change' listener
        event: 'change',
        result: (rte, action) => rte.insertHTML(action.btn.firstChild.value),
        // Reset the select on change
        update: (rte, action) => {
          action.btn.firstChild.value = ''
        },
      },
    ],
  },
  //...
})

``` 
this seems to do the trick

**Comment by HelveticaScenario** [comment] 2019-05-11 00:11
> Probably in the next release, this feature will be available.
> ![textable](https://user-images.githubusercontent.com/11614725/55838123-a8791000-5b23-11e9-8866-c2059a972fc5.gif)
> 
> So `textable` will be just another property, this will allow any component to be dropped inside Text components.
> Here is the code of the component from the example above:
> 
> ```js
> // Define a component with `textable` property
> editor.DomComponents.addType('var-placeholder', {
>       model: {
>         defaults: {
>           textable: 1,
>           placeholder: 'VARIABLE-1',
>         },
>         toHTML() {
>           return `{{ ${this.get('placeholder')} }}`;
>         },
>       },
> 	  // The view below it's just an example of creating a different UX
>       view: {
>         tagName: 'span',
>         events: {
>           'change': 'updatePlh',
>         },
>         // Update the model once the select is changed
>         updatePlh(ev) {
>           this.model.set({ placeholder: ev.target.value });
>           this.updateProps();
>         },
>         // When we blur from a TextComponent, all its children components are
>         // flattened via innerHTML and parsed by the editor. So to keep the state
>         // of our props in sync with the model so we need to expose props in the HTML
>         updateProps() {
>           const { el, model } = this;
>           el.setAttribute('data-gjs-placeholder',  model.get('placeholder'));
>         },
>         onRender() {
>           const { model, el } = this;
>           const currentPlh = model.get('placeholder');
>           const select = document.createElement('select');
>           const options = [ 'VARIABLE-1', 'VARIABLE-2', 'VARIABLE-3' ];
>           select.innerHTML = options.map(item => `<option value="${item}" ${item === currentPlh ? 'selected' : ''}>
> 			${item}
> 		  </option>`).join('');
>           while (el.firstChild) el.removeChild(el.firstChild);
>           el.appendChild(select);
>           select.setAttribute('style', 'padding: 5px; border-radius: 3px; border: none; -webkit-appearance: none;');
>           this.updateProps();
>         },
>       }
>     });
> 	
> 	// Use the component in blocks
>     editor.BlockManager.add('simple-block', {
>       label: 'Textable block',
>       content: { type: 'var-placeholder' },
>     });
> ```

This code isn't working for me on `0.14.61`, nothing is shown. It doesn't seem that the `onRender` method is ever called.

**Comment by artf** [comment] 2019-05-11 23:14
> This code isn't working for me on `0.14.61`, nothing is shown. It doesn't seem that the `onRender` method is ever called.

@HelveticaScenario mmm seems like at the end, after adding other features, I've introduced some regression. Seems to work only if the textable component is placed outside before being dropped in the text one

**Comment by aklatzke** [comment] 2019-05-13 16:39
@artf Are there any workarounds for this issue in the meantime?

**Comment by artf** [comment] 2019-05-19 18:05
> @artf Are there any workarounds for this issue in the meantime?

I'd have said it if there was one

**Comment by eduardonunesp** [comment] 2019-05-31 00:01
@artf I'd like to know if you guys have an idea when the next release with the fix will be available, thanks for the fix!

**Comment by mynamespace** [comment] 2020-04-13 21:18
> 
> 
> Probably in the next release, this feature will be available.
> ![textable](https://user-images.githubusercontent.com/11614725/55838123-a8791000-5b23-11e9-8866-c2059a972fc5.gif)
> 
> So `textable` will be just another property, this will allow any component to be dropped inside Text components.
> Here is the code of the component from the example above:
> 
> ```js
> // Define a component with `textable` property
> editor.DomComponents.addType('var-placeholder', {
>       model: {
>         defaults: {
>           textable: 1,
>           placeholder: 'VARIABLE-1',
>         },
>         toHTML() {
>           return `{{ ${this.get('placeholder')} }}`;
>         },
>       },
> 	  // The view below it's just an example of creating a different UX
>       view: {
>         tagName: 'span',
>         events: {
>           'change': 'updatePlh',
>         },
>         // Update the model once the select is changed
>         updatePlh(ev) {
>           this.model.set({ placeholder: ev.target.value });
>           this.updateProps();
>         },
>         // When we blur from a TextComponent, all its children components are
>         // flattened via innerHTML and parsed by the editor. So to keep the state
>         // of our props in sync with the model so we need to expose props in the HTML
>         updateProps() {
>           const { el, model } = this;
>           el.setAttribute('data-gjs-placeholder',  model.get('placeholder'));
>         },
>         onRender() {
>           const { model, el } = this;
>           const currentPlh = model.get('placeholder');
>           const select = document.createElement('select');
>           const options = [ 'VARIABLE-1', 'VARIABLE-2', 'VARIABLE-3' ];
>           select.innerHTML = options.map(item => `<option value="${item}" ${item === currentPlh ? 'selected' : ''}>
> 			${item}
> 		  </option>`).join('');
>           while (el.firstChild) el.removeChild(el.firstChild);
>           el.appendChild(select);
>           select.setAttribute('style', 'padding: 5px; border-radius: 3px; border: none; -webkit-appearance: none;');
>           this.updateProps();
>         },
>       }
>     });
> 	
> 	// Use the component in blocks
>     editor.BlockManager.add('simple-block', {
>       label: 'Textable block',
>       content: { type: 'var-placeholder' },
>     });
> ```

this works for me, but how could we parse back (using isComponent()) when loading the content inside the editor? I would like to create merge tags/shortcodes with attributes using these draggable text components.

**Comment by Joshmamroud** [comment] 2020-07-14 13:28
It works on its own however any time I try to drop it in a text block I get this error:

`grapes.min.js:2 Uncaught TypeError: Cannot read property 'attributes' of undefined
    at r.updateAttributes (grapes.min.js:2)
    at renderAttributes (grapes.min.js:2)
    at render (grapes.min.js:2)
    at r.move (grapes.min.js:11)
    at grapes.min.js:11
    at Array.forEach (<anonymous>)
    at r.endMove (grapes.min.js:11)
    at Et (grapes.min.js:2)
    at r.<anonymous> (grapes.min.js:2)
    at r.endMove (grapes.min.js:2)
    at i (grapes.min.js:11)
    at t.value (grapes.min.js:11)
    at t.value (grapes.min.js:11)
    at Et (grapes.min.js:2)
    at HTMLDivElement.<anonymous> (grapes.min.js:2)
    at HTMLDivElement.<anonymous> (grapes.min.js:2)
` 

I've literally copied and pasted the code from the example for both the dom component and block. I'm trying to add the placeholder-var block to the text block from the basic blocks plugin.

I don't know where this is coming from because it's minified and I can't figure out how to use the unminified version of the npm package.

Any help would be greatly appreciated.

Thanks!

**Comment by jamejillagit** [comment] 2020-08-07 10:04
Hi @artf 
First of all, thank you for all your work. I am discovering Grapesjs and it is truly awesome.

I am experiencing the same issue as @Joshmamroud and was wondering if we are doing something wrong or whether there is some known issue with this code.

Any help would be very much appreciated.

Regards

**Comment by ranashadab** [comment] 2020-09-23 12:28
@jamejillagit @Joshmamroud  If you guys are have still not come across the answer, the thanks to @mwidner, this bug is due changes in new version. As mentioned in bug #2771  it still works in version 0.16.3. So, u guys can change to previous version like me if that serves the purpose.

**Comment by tudor-ooo** [comment] 2021-01-12 01:02
I have the same error :-(
```
Uncaught TypeError: Cannot read property 'attributes' of undefined
    at r.updateAttributes (grapes.min.js:2)
    at renderAttributes (grapes.min.js:2)
    at render (grapes.min.js:2)
    at r.move (grapes.min.js:11)
    at grapes.min.js:11
    at Array.forEach (<anonymous>)
    at r.endMove (grapes.min.js:11)
    at Ft (grapes.min.js:2)
    at r.<anonymous> (grapes.min.js:2)
    at r.endMove (grapes.min.js:2)
    at i (grapes.min.js:11)
    at t.value (grapes.min.js:11)
    at t.value (grapes.min.js:11)
    at Ft (grapes.min.js:2)
    at HTMLDivElement.<anonymous> (grapes.min.js:2)
    at HTMLDivElement.<anonymous> (grapes.min.js:2)
```

(grapesjs - 0.16.27)

**Comment by hanna404** [comment] 2021-01-21 10:01
Hello I am having the same issue of @tudor-ooo and @Joshmamroud , did you guys found any solution ?

**Comment by hanna404** [comment] 2021-01-21 10:01
can we re-open this case @artf  ?

**Comment by artf** [comment] 2021-01-27 21:23
#2771
