### ISSUE TITLE
Setting backgroud image results in duplicate style rules

### ISSUE THREAD

**Issue by TheMysticMan** [artf/grapesjs#933] opened 2018-03-07 23:48 UTC
Hi @artf,

I have one strange little problem.
I have a custom trait which has an implementation for setting images and background images. 
When I set the background image a second time by using the code below I'm getting duplicated styling rules on the element Id.

```js
var style = self.target.getStyle();
// style is empty even though the stylemanager shows the default background image from the class style rule
style['background-image'] ='url("' + newUrl + '")';
self.target.setStyle(style);
```

I already played around a bit with the forceClass and avoidInlineStyle but it doesn't really help with this problem.
Maybe related to this problem: The element also has a class with a default background image. When I open the StyleManager I only see that background image in there. Not the images from the Id style rules. Looks like it doesn't really use them at all?

Thanks in advance!

**Comment by artf** [comment] 2018-03-08 13:43
Duplicate of #932

**Closed by artf** 2018-03-08 13:43 UTC
