### ISSUE TITLE
editor.load possibly causes memory leak

### ISSUE THREAD

**Issue by varadero** [artf/grapesjs#2403] opened 2019-11-12 21:02 UTC
How to reproduce:
- Naviagate to https://grapesjs.com/demo.html
- Open browser console (Chrome) and type the following: `setInterval(() => editor.load(), 1000)` and press Enter
- Go to "Memory" tab (Chrome) and look at the memory usage

What happens:
The memory is constantly increasing. If you open Chrome's "Performance monitor" you can also see "DOM nodes" and "JS event listeners" constantly increasing. After about 3 minutes "JS Heap size" increases from 24MB to 1000MB, "JS event listeners" increases from about 1600 to 50000+, "DOM nodes" from 8600 to 100000+. After some time the browser tab will crash because of the high memory consumption.

The same happens also if you have very simple grapesjs project and place a single block in the canvas and start in an interval a call to `editor.load()`.

**Comment by varadero** [comment] 2019-11-15 10:28
This is important. If not fixed, it makes GrapesJS dangerous to use especially in SPA applications.

**Comment by artf** [comment] 2019-11-17 23:03
I'll check it out, but any help is welcome

**Comment by diazemiliano** [comment] 2020-09-03 16:20
I'm having the same issue here.
Even after destroy the editor, the issue remains.

**Comment by Nelida27** [comment] 2021-09-28 13:57
Hello @varadero @artf ,
Any update about this issue, since I have the same problem.

**Comment by artf** [comment] 2021-10-03 16:02
Not really, I've refactored a lot of modules since this issue by taking into account the memory leak problem but was not really focused on inspecting each module so, I guess the issue is still here. I'm closing this one in favor of #1470, probably I'll be back on this issue soon and will report any possible update there.

**Closed by artf** 2021-10-03 16:02 UTC
Labels: help wanted

**Comment by samehdoush** [comment] 2023-03-16 14:36
I'm having the same issue here.
Even after destroy the editor, the issue remains.

**Comment by zhixXiang** [comment] 2023-07-04 14:16
I'm having the same issue here.
Everytime load increase the memory

**Comment by zhixXiang** [comment] 2023-07-04 15:07
@artf  I use below code on server side
`
let editor: Editor | null = grapesjs.init({ headless: true });
editor.loadProjectData(myJson);
`

this cause memory leak
Everytime loadProjectData increase the memory, my server out of memory soon.

**Comment by YousofSayed** [comment] 2025-09-28 04:55
I have the same issue. Has it been solved yet?
